# Golden-output tests: pin the numbers, so that a refactor that changes a result is caught.
#
# The reference values are generated by R itself on first run (tests/testthat/_golden/golden.rds) and
# committed thereafter. Regenerate deliberately with:
#     unlink("tests/testthat/_golden", recursive = TRUE); testthat::test_file("tests/testthat/test-golden.R")
# Never regenerate to make a failing test pass: a change here means a number moved, and the reason
# must be understood first.
#
# The reference is NOT shipped in the source archive, because it must be produced by the same R and package
# versions the maintainer tests against. On a fresh checkout this test therefore FAILS on its first run and
# writes the reference; commit that file and the test becomes a real regression check from then on.

golden_dir <- testthat::test_path("_golden")
golden_file <- file.path(golden_dir, "golden.rds")

golden_data <- function(seed = 42, n = 80) {
  set.seed(seed)
  do.call(rbind, lapply(seq_len(n), function(i) {
    q <- rnorm(1)
    ls <- max(4, round(12 + 4 * q))
    ages <- seq_len(ls)
    data.frame(id = sprintf("i%03d", i), age = ages,
               trait = 10 + rnorm(1) + (-0.2 + 0.08 * q) * ages + rnorm(ls, 0, 0.7),
               LS = ls, grp = sprintf("g%d", i %% 5 + 1), stringsAsFactors = FALSE)
  }))
}
golden_map <- function(...) {
  m <- list(id = "id", age = "age", trait = "trait", alr = "__AUTO_LAST__", life = "LS",
            entry = "__AUTO_FIRST__", covars = character(0), cov_factor = character(0),
            cov_int = character(0), group = "", nested = TRUE, random = character(0),
            censor = "", censor_value = "", condition = "", trials = "", start_mode = "afr",
            start_age = NA_real_, age_round = NA_real_, cov_age = character(0))
  utils::modifyList(m, list(...))
}

current_golden <- function() {
  d <- golden_data()
  b <- standardise_data(d, golden_map())
  out <- list()
  for (fn in c("Linear", "Quadratic")) {
    r <- fit_model_suite(b$data, b$meta, models = c("M1", "M2", "M4", "M6"),
                         age_function = fn, family = "gaussian")
    out[[paste0("aic_", fn)]] <- round(stats::setNames(r$aic$AIC, r$aic$Model), 4)
    out[[paste0("delta_", fn)]] <- round(stats::setNames(r$aic$Delta_AIC, r$aic$Model), 4)
    cf <- r$coefficients
    if (!is.null(cf) && nrow(cf)) {
      key <- paste(cf$Model, cf$Raw_term, sep = "|")
      out[[paste0("coef_", fn)]] <- round(stats::setNames(cf$Estimate, key), 4)
    }
  }
  dec <- decomposition_trajectory(b$data)
  out$decomp_age <- round(dec$age, 4)
  out$decomp_fitted <- round(dec$fitted, 4)
  out$decomp_npairs <- as.integer(dec$n_pairs)
  im <- individual_metrics(b$data)
  out$metrics <- round(c(n_id = nrow(im), mean_alr = mean(im$alr, na.rm = TRUE),
                         mean_records = mean(im$n_trait, na.rm = TRUE)), 4)
  prep <- prepare_model_data(b$data, "Quadratic", character(0), TRUE, FALSE, character(0))
  out$basis <- round(c(mean_f1 = mean(prep$data$f1), sd_f1 = stats::sd(prep$data$f1),
                       mean_f2 = mean(prep$data$f2), mean_ALR = mean(prep$data$ALR)), 4)
  out
}

test_that("model AICs, coefficients and the decomposition match the stored reference", {
  cur <- current_golden()
  if (!file.exists(golden_file)) {
    # Write the reference so it can be inspected and committed, then FAIL. A shipped package without a
    # committed reference would otherwise certify whatever the code happens to do on the user's machine,
    # which is not a regression test at all.
    dir.create(golden_dir, showWarnings = FALSE, recursive = TRUE)
    saveRDS(cur, golden_file)
    fail(paste("No committed golden reference was found, so this run has no regression test.",
               "A reference has just been written to tests/testthat/_golden/golden.rds:",
               "inspect it, commit it, and re-run. Until then the golden tests certify nothing."))
  }
  ref <- readRDS(golden_file)
  expect_setequal(names(cur), names(ref))
  for (k in names(ref)) {
    expect_equal(cur[[k]], ref[[k]], tolerance = 1e-6,
                 info = sprintf("golden element '%s' changed: a stored result moved, so find out why before regenerating", k))
  }
})

test_that("the exported script reproduces the fitted AIC values", {
  d <- golden_data()
  b <- standardise_data(d, golden_map())
  r <- fit_model_suite(b$data, b$meta, models = c("M1", "M2", "M4"), age_function = "Quadratic", family = "gaussian")
  code <- model_r_code(r, b$meta)
  expect_true(is.character(code) && length(code) > 0)
  # the script must name every fitted model and the same family, so that running it reproduces the analysis
  for (m in c("M1", "M2", "M4")) expect_true(any(grepl(m, code, fixed = TRUE)))
  expect_true(any(grepl("gaussian|lmer", code)))
  again <- fit_model_suite(b$data, b$meta, models = c("M1", "M2", "M4"), age_function = "Quadratic", family = "gaussian")
  expect_equal(r$aic$AIC, again$aic$AIC, tolerance = 1e-10)
})

test_that("every plotting function returns a plot without error on real and degenerate data", {
  d <- golden_data()
  b <- standardise_data(d, golden_map())
  small <- b$data[b$data$id %in% unique(b$data$id)[1:2], , drop = FALSE]
  one_age <- b$data[b$data$age == min(b$data$age), , drop = FALSE]
  # plots are built inside server.R rather than as exported functions, so only the package-level
  # plotting helpers can be smoke-tested here; the server plots need a Shiny session test
  fns <- c("proxy_pair_plot", "empty_plot")
  for (fn in fns) {
    if (!exists(fn)) next
    f <- get(fn)
    p <- tryCatch(
      if (identical(fn, "empty_plot")) f("nothing to show") else f(b$data$age, b$data$trait, "age", "trait"),
      error = function(e) e)
    expect_false(inherits(p, "error"),
                 info = sprintf("%s errored: %s", fn, if (inherits(p, "error")) conditionMessage(p) else ""))
    expect_true(inherits(p, "ggplot") || inherits(p, "gg"))
  }
})
