# Golden results: freezes representative outputs of the disappR engine so that a refactor can be checked for exact
# equivalence - formulas, analysed rows, coefficients, log-likelihoods, AIC, predictions, validity and fit messages,
# notes, the pre-fit row check, the decomposition, observed means and the exported code.
#
# Works on any version with the app in inst/app (0.9.9 and later). Run both versions on the same machine:
#   Rscript tests/golden/golden_capture.R /path/to/disappR_0.9.9 golden_0.9.9.rds
#   Rscript tests/golden/golden_capture.R .                      golden_new.rds
#   Rscript tests/golden/golden_compare.R golden_0.9.9.rds golden_new.rds
args <- commandArgs(trailingOnly = TRUE)
root <- normalizePath(if (length(args) >= 1) args[[1]] else ".", mustWork = TRUE)
out <- if (length(args) >= 2) args[[2]] else "golden.rds"
out <- file.path(normalizePath(dirname(out), mustWork = TRUE), basename(out))
suppressPackageStartupMessages(library(shiny))
owd <- setwd(file.path(root, "inst", "app"))
source("global.R")
set.seed(1)
keep <- function(expr) tryCatch(expr, error = function(e) structure(conditionMessage(e), class = "golden_error"))
strip_version <- function(code) {
  if (!is.character(code)) return(code)
  lines <- strsplit(code, "\n", fixed = TRUE)[[1]]
  lines[!grepl("^# (Code generated by disappR|Versions in the app session)", lines)]
}
summarise_fit <- function(r, meta, ages) {
  if (inherits(r, "golden_error") || !is.list(r)) return(r)
  if (!isTRUE(r$ok)) return(list(ok = FALSE, message = r$message))
  core <- r[setdiff(names(r), c("fits", "data", "provenance"))]
  core <- core[!vapply(core, function(x) is.function(x) || is.environment(x), logical(1))]
  loglik <- vapply(r$fits, function(f) tryCatch(as.numeric(stats::logLik(f)), error = function(e) NA_real_), numeric(1))
  preds <- lapply(names(r$fits), function(m) {
    p <- keep(predict_population_curve(r$fits[[m]], r, ages))
    if (is.data.frame(p)) p$fitted else p
  })
  names(preds) <- names(r$fits)
  list(ok = TRUE, core = core, loglik = loglik, rows = paste(r$data$id, r$data$age, sep = "@"), predictions = preds,
       notes = keep(consistency_notes(r)), code = strip_version(keep(model_r_code(r, meta))))
}
one_analysis <- function(raw, map, models, fun, family, extra = NULL) {
  b <- keep(standardise_data(raw, map))
  if (inherits(b, "golden_error")) return(b)
  ages <- seq(min(b$data$age, na.rm = TRUE), max(b$data$age, na.rm = TRUE), length.out = 25)
  r <- keep(fit_model_suite(b$data, b$meta, models, fun, family, extra = extra))
  dry <- keep(fit_model_suite(b$data, b$meta, models, fun, family, extra = extra, dry_run = TRUE))
  list(n_rows = nrow(b$data), meta_names = sort(names(b$meta)), fit = summarise_fit(r, b$meta, ages), dry = dry,
       decomposition = keep(decomposition_trajectory(b$data)), observed = keep(observed_trajectory(b$data)))
}
analyses <- list()
for (key in names(EXAMPLES)) {
  ex <- EXAMPLES[[key]]
  raw <- load_example_file(ex$file)
  if (is.null(raw)) next
  if (!is.null(ex$subset)) raw <- raw[!is.na(raw[[ex$subset$var]]) & as.character(raw[[ex$subset$var]]) %in% ex$subset$levels, , drop = FALSE]
  cat("example", key, "\n")
  analyses[[key]] <- one_analysis(raw, ex$mapping, ex$models %||% MODEL_IDS, ex$age_function %||% "Quadratic",
                                  ex$family %||% "gaussian", ex$extra)
}
designs <- list(
  gauss_both = list(n_id = 150, seed = 11, sd_type = "both"),
  none_mcar = list(n_id = 150, seed = 12, sd_type = "none", missingness = "mcar"),
  missing_when_old = list(n_id = 150, seed = 13, missingness = "mwo"),
  appearance = list(n_id = 150, seed = 14, afr_mode = "individual", sa_type = "both"),
  diet_families = list(n_id = 150, seed = 15, diet = TRUE, groups = TRUE),
  counts = list(n_id = 150, seed = 16, trait = "count_pois"),
  cubic = list(n_id = 150, seed = 17, form = "Cubic"),
  short_lives = list(n_id = 150, seed = 18, mean_ls = 5))
simulations <- list()
for (nm in names(designs)) {
  cat("simulation", nm, "\n")
  raw <- simulate_toy_data(designs[[nm]])
  fam <- if (identical(designs[[nm]]$trait, "count_pois") && isTRUE(HAS_GLMMTMB)) "poisson" else "gaussian"
  simulations[[nm]] <- c(list(data = raw), one_analysis(raw, toy_mapping(raw), c("M1", "M2", "M3", "M4", "M5", "M6", "M7", "M8"), "Quadratic", fam))
}
setwd(owd)
saveRDS(list(R = R.version.string, packages = vapply(c("lme4", "glmmTMB", "lmerTest"), function(p) tryCatch(as.character(utils::packageVersion(p)), error = function(e) NA_character_), character(1)),
             analyses = analyses, simulations = simulations), out)
cat("Golden results written to", out, "\n")
