# disappR engine - Export: reproducible R code for sections and model comparisons, analysis data, and saved-result reports.
# Moved verbatim from inst/app/global.R (0.9.9); do not edit here without the golden tests (tests/golden/).

# ---------------------------------------------------------------------------
# Section R scripts: the app's own functions that a section needs, found through their calls, written out
# so that a script runs without disappR
# ---------------------------------------------------------------------------
app_code_closure <- function(entry, env = environment(standardise_data)) {
  seen <- character(0)
  todo <- entry
  while (length(todo)) {
    f <- todo[[1]]
    todo <- todo[-1]
    if (f %in% seen || !exists(f, envir = env, inherits = FALSE)) next
    seen <- c(seen, f)
    obj <- get(f, envir = env, inherits = FALSE)
    if (is.function(obj) && requireNamespace("codetools", quietly = TRUE)) {
      g <- tryCatch(codetools::findGlobals(obj, merge = TRUE), error = function(e) character(0))
      todo <- c(todo, setdiff(g, seen))
    }
  }
  seen
}

app_code_definitions <- function(nms, env = environment(standardise_data)) {
  has_pkg <- c(HAS_GLMMTMB = "glmmTMB", HAS_LMERTEST = "lmerTest", HAS_DHARMA = "DHARMa")
  lab <- function(n) if (identical(make.names(n), n)) n else paste0("`", n, "`")
  objs <- lapply(nms, function(n) get(n, envir = env, inherits = FALSE))
  is_fun <- vapply(objs, is.function, logical(1))
  small <- vapply(objs, function(o) is.function(o) || as.numeric(utils::object.size(o)) < 2e5, logical(1))
  one <- function(n, o) {
    if (n %in% names(has_pkg)) return(sprintf("%s <- requireNamespace(\"%s\", quietly = TRUE)", n, has_pkg[[n]]))
    paste0(lab(n), " <- ", paste(deparse(o, width.cutoff = 500L), collapse = "\n"))
  }
  keep <- small
  c(unlist(Map(one, nms[keep & !is_fun], objs[keep & !is_fun]), use.names = FALSE),
    unlist(Map(one, nms[keep & is_fun], objs[keep & is_fun]), use.names = FALSE))
}

# The rows and variables a model comparison used, for exact reproduction outside the app.
analysis_data_export <- function(res) {
  d <- res$data
  if (!is.data.frame(d) || !nrow(d)) return(data.frame())
  d[] <- lapply(d, function(x) if (is.factor(x)) as.character(x) else x)
  d
}

# ---------------------------------------------------------------------------
# Reproducible R code for the fitted comparison
# ---------------------------------------------------------------------------
model_r_code <- function(res, meta, source_label = "your_data.csv", source_type = "upload") {
  if (isTRUE(res$nonlinear)) return(model_r_code_nonlinear(res, meta, source_label))
  map <- meta$map
  q <- function(x) paste0('"', x, '"')
  ap <- res$age_params
  pp <- res$proxy_params
  num <- function(x) format(x, digits = 10)
  lines <- c(
    paste0("# Code generated by disappR ", DISAPPR_VERSION, " - reproduces the app's model comparison"),
    dependency_versions_line(),
    if (identical(res$family, "gaussian")) "library(lme4)" else "library(glmmTMB)",
    paste0("dat <- read.csv(", q(source_label), ", stringsAsFactors = FALSE, check.names = FALSE, colClasses = c(", q(map$id), " = \"character\"))"),
    if (!is.null(meta$subset)) sprintf("dat <- dat[!is.na(dat[[%s]]) & as.character(dat[[%s]]) %%in%% c(%s), ]  # subset used in the app",
                                       q(meta$subset$var), q(meta$subset$var), paste(q(meta$subset$levels), collapse = ", ")) else NULL,
    paste0("dat$id <- trimws(as.character(dat[[", q(map$id), "]]))"),
    if (isTRUE(meta$has_group)) paste0("dat$group <- as.character(dat[[", q(map$group), "]])") else NULL,
    if (isTRUE(meta$has_group2)) paste0("dat$group2 <- as.character(dat[[", q(map$group2), "]])") else NULL,
    if (isTRUE(meta$has_group2) && isTRUE(meta$nested)) "dat$group <- ifelse(is.na(dat$group) | is.na(dat$group2), dat$group, paste(dat$group2, dat$group, sep = \"/\"))  # groups nested in top-level groups" else NULL,
    if (isTRUE(meta$has_group) && isTRUE(meta$nested)) "dat$id <- ifelse(is.na(dat$group), dat$id, paste(dat$group, dat$id, sep = \"/\"))  # nested: (1 | group) + (1 | group/ID)" else NULL,
    paste0("dat$age <- as.numeric(dat[[", q(map$age), "]])"),
    if (is.finite(meta$age_round %||% NA_real_)) sprintf("dat$age <- round(dat$age / %s) * %s  # ages rounded as in the app", num(meta$age_round), num(meta$age_round)) else NULL,
    paste0("dat$trait <- as.numeric(dat[[", q(map$trait), "]])"),
    if (res$family %in% BINOMIAL_FAMILIES && isTRUE(meta$has_trials)) paste0("dat$.trials <- as.numeric(dat[[", q(meta$trials_col), "]])  # number of binomial trials (prior weights)") else NULL,
    "dat <- dat[!is.na(dat$id) & is.finite(dat$age), ]",
    if (isTRUE(meta$alr_mapped)) paste0("dat$ALR_raw <- as.numeric(dat[[", q(map$alr), "]])") else "dat$ALR_raw <- ave(dat$age, dat$id, FUN = max)  # age at last record",
    if (isTRUE(meta$entry_mapped)) paste0("dat$AFR_raw <- as.numeric(dat[[", q(map$entry), "]])") else "dat$AFR_raw <- ave(dat$age, dat$id, FUN = min)  # age at first record",
    if (isTRUE(meta$has_life) && !isTRUE(meta$life_auto)) paste0("dat$LS_raw <- as.numeric(dat[[", q(map$life), "]])") else "dat$LS_raw <- NA_real_",
    if (isTRUE(meta$has_censor)) sprintf("dat$LS_raw[dat$id %%in%% dat$id[as.character(dat[[%s]]) %%in%% %s]] <- NA  # censored individuals: lifespan unknown",
                                         q(map$censor), q(map$censor_value)) else NULL,
    if (identical(meta$dup_action, "mean")) "# NOTE: the app averaged duplicate ID x age records; do the same here before fitting" else NULL,
    "dat <- dat[is.finite(dat$trait), ]",
    if (res$family %in% BINOMIAL_FAMILIES && isTRUE(meta$has_trials)) "dat <- dat[is.finite(dat$.trials) & dat$.trials > 0, ]  # rows without a positive number of trials are dropped, as in the app" else NULL,
    "# individual-level centring/scaling constants used by the app",
    sprintf("dat$ALR <- (dat$ALR_raw - %s) / %s", num(pp$ALR[["centre"]]), num(pp$ALR[["scale"]])),
    sprintf("dat$AFR <- (dat$AFR_raw - %s) / %s", num(pp$AFR[["centre"]]), num(pp$AFR[["scale"]])),
    sprintf("dat$LS  <- (dat$LS_raw - %s) / %s", num(pp$LS[["centre"]]), num(pp$LS[["scale"]])),
    if (isTRUE(res$among %in% c("same", "consistent"))) "for (v in c(\"ALR\", \"AFR\", \"LS\")) { dat[[paste0(v, 2)]] <- dat[[v]]^2; dat[[paste0(v, 3)]] <- dat[[v]]^3 }  # polynomial among-individual terms" else NULL
  )
  z <- sprintf("(dat$age - %s) / %s", num(ap$mean_age), num(ap$sd_age))
  basis_lines <- switch(ap$fun,
    Linear = sprintf("dat$f1 <- %s", if (ap$standardise) z else "dat$age"),
    Quadratic = c(sprintf("dat$f1 <- %s", if (ap$standardise) z else "dat$age"), "dat$f2 <- dat$f1^2"),
    Cubic = c(sprintf("dat$f1 <- %s", if (ap$standardise) z else "dat$age"), "dat$f2 <- dat$f1^2", "dat$f3 <- dat$f1^3"),
    Logarithmic = {
      lx <- if (ap$all_positive) "log(dat$age)" else sprintf("log(dat$age - %s + 1)", num(ap$min_age))
      sprintf("dat$f1 <- %s", if (ap$standardise) sprintf("(%s - %s) / %s", lx, num(ap$mean_log), num(ap$sd_log)) else lx)
    },
    "Asymptotic exponential" = sprintf("dat$f1 <- %s", if (ap$standardise) sprintf("(exp(-%s) - %s) / %s", z, num(ap$mean_exp), num(ap$sd_exp)) else sprintf("exp(-%s)", z))
  )
  lines <- c(lines, basis_lines)
  for (nm in res$basis) {
    lines <- c(lines, sprintf("dat$mean_%s <- ave(dat$%s, dat$id, FUN = mean); dat$delta_%s <- dat$%s - dat$mean_%s", nm, nm, nm, nm, nm))
  }
  if (identical(res$among, "same") && "f1" %in% res$basis)
    lines <- c(lines, "dat$mean_f1_2 <- dat$mean_f1^2; dat$mean_f1_3 <- dat$mean_f1^3  # powers of mean age ('same polynomial order')")
  for (cv in meta$covars) {
    lines <- c(lines, if (identical(meta$cov_types[[cv]] %||% "", "continuous")) {
      sprintf("dat$%s <- suppressWarnings(as.numeric(dat[[%s]]))  # continuous covariate", cv, q(meta$cov_labels[[cv]]))
    } else {
      sprintf("dat$%s <- factor(dat[[%s]])  # categorical covariate", cv, q(meta$cov_labels[[cv]]))
    })
  }
  if (isTRUE(meta$has_group)) lines <- c(lines, "dat$group <- factor(dat$group)")
  if (isTRUE(meta$has_group2)) lines <- c(lines, "dat$group2 <- factor(dat$group2)")
  for (rt in res$random_terms %||% character(0)) {
    lines <- c(lines, sprintf("dat$%s <- factor(dat[[%s]])", rt, q(meta$random_labels[[rt]])))
  }
  lines <- c(lines, "dat$id <- factor(dat$id)")
  i_read <- which(startsWith(lines, "dat <- read.csv("))[1]
  if (is.finite(i_read)) {
    fac_cols <- names(res$data)[vapply(res$data, is.factor, logical(1))]
    lines <- append(lines, c(
      "# Exact reproduction: download 'Analysis data (CSV)' from the app (next to 'Download R script') and save it next to this",
      "# script. The script then uses the rows and variables the app fitted; without it, it rebuilds them from the raw file.",
      "app_data_file <- \"disappR_analysis_data.csv\"",
      "use_app_data <- file.exists(app_data_file)",
      "if (use_app_data) {",
      "  dat <- read.csv(app_data_file, stringsAsFactors = FALSE, check.names = FALSE, colClasses = c(id = \"character\"))",
      if (length(fac_cols)) paste0("  for (v in intersect(c(", paste(q(fac_cols), collapse = ", "), "), names(dat))) dat[[v]] <- factor(dat[[v]])") else NULL,
      "} else {"), after = i_read - 1)
    lines <- c(lines, "}")
  }
  vars <- unique(unlist(lapply(res$formulas, function(s) all.vars(stats::as.formula(paste("trait ~", s))))))
  vars <- c(vars, "id", if (isTRUE(meta$has_group)) "group", if (isTRUE(meta$has_group2)) "group2", res$random_terms %||% character(0))
  lines <- c(lines, paste0("dat <- dat[complete.cases(dat[, c(", paste(q(vars), collapse = ", "), ")]), ]  # common rows for AIC"))
  call_for <- function(m) {
    f <- paste("trait ~", res$formulas[[m]], "+", res$random)
    if (identical(res$family, "gaussian")) {
      sprintf("%s <- lmer(%s, data = dat, REML = FALSE, control = lmerControl(optimizer = \"bobyqa\"))", tolower(m), f)
    } else {
      fam <- switch(res$family, poisson = "poisson()", zip = "poisson()", nbinom1 = "nbinom1()", zinb1 = "nbinom1()",
                    binomial = "binomial()", betabinomial = "betabinomial()", "nbinom2()")
      zi <- if (res$family %in% ZI_FAMILIES) res$zi else "~0"
      wt <- if (res$family %in% BINOMIAL_FAMILIES && isTRUE(meta$has_trials)) ", weights = .trials" else ""
      sprintf("%s <- glmmTMB(%s, family = %s, ziformula = %s, data = dat%s)", tolower(m), f, fam, zi, wt)
    }
  }
  fitted <- names(res$fits)
  # the same disappR engine as the app when that version is installed, otherwise the standalone reconstruction
  standalone <- c(lines[-(1:3)], vapply(fitted, call_for, character(1)))
  lines <- c(lines[1:3],
             if (length(res$provenance)) paste("#", provenance_lines(res$provenance)) else NULL,
             engine_script_lines(res, meta, source_label, source_type),
             ifelse(nzchar(standalone), paste0("  ", standalone), standalone),
             "}",
             paste0("AIC(", paste(tolower(fitted), collapse = ", "), ")"),
             if (length(fitted)) plot_code_lines(res, meta) else NULL)
  paste(lines, collapse = "\n")
}

# Opening of the exported script's engine branch: with the same disappR version installed, the script reads, prepares
# and fits the data with the app's own functions and settings; the standalone reconstruction follows in the else branch.
engine_script_lines <- function(res, meta, source_label, source_type = "upload") {
  q <- function(x) paste0('"', x, '"')
  key <- if (identical(source_type, "example")) names(EXAMPLES)[vapply(EXAMPLES, function(e) identical(e$file, source_label), logical(1))] else character(0)
  read_line <- if (length(key)) {
    sprintf("  raw <- disappR::disappr_example(%s)$data", q(key[[1]]))
  } else {
    sprintf("  raw <- disappR:::read_user_csv(%s, %s)$data", q(source_label), q(basename(source_label)))
  }
  models <- names(res$status)
  if (!length(models)) models <- names(res$fits)
  c(sprintf("use_engine <- requireNamespace(\"disappR\", quietly = TRUE) && identical(as.character(utils::packageVersion(\"disappR\")), %s)", q(DISAPPR_VERSION)),
    "if (use_engine) {",
    "  # the disappR engine - the same code and settings as the app - reads, prepares and fits the data",
    "  library(disappR)",
    read_line,
    if (!is.null(meta$subset)) sprintf("  raw <- raw[!is.na(raw[[%s]]) & as.character(raw[[%s]]) %%in%% c(%s), ]  # subset used in the app",
                                       q(meta$subset$var), q(meta$subset$var), paste(q(meta$subset$levels), collapse = ", ")) else NULL,
    paste0("  x <- disappr_prepare(raw, ", paste(deparse(meta$map, width.cutoff = 500L), collapse = " "), ", dup_action = ",
           q(meta$dup_action %||% "keep"), ")"),
    paste0("  fit <- disappr_fit(x, models = ", deparse1(models), ", age_function = ", q(res$age_function), ", family = ", q(res$family),
           ", random_slope = ", deparse1(res$random_request %||% res$random_structure), ", standardise = ", isTRUE(res$standardise),
           ", zi_str = ", q(res$zi %||% "~1"), ", among = ", q(res$among %||% "linear"), ", include_invalid = ", isTRUE(res$include_invalid),
           ", extra = ", paste(deparse(res$extra, width.cutoff = 500L), collapse = " "), ")"),
    "  print(disappr_compare(fit))",
    "  dat <- fit$data",
    "  for (m in names(fit$fits)) assign(tolower(m), fit$fits[[m]])",
    "} else {",
    "  # without the same disappR version: a standalone reconstruction with lme4 / glmmTMB")
}

# R code for the model predictions trajectory figure: the fitted models' predictions (computed as in the app),
# observed means and the decomposition. Appended to the exported model script.
plot_code_lines <- function(res, meta) {
  ap <- res$age_params
  num <- function(x) format(x, digits = 10)
  q <- function(x) paste0('"', x, '"')
  zf <- sprintf("(age - %s) / %s", num(ap$mean_age), num(ap$sd_age))
  f1 <- if (isTRUE(ap$standardise)) zf else "age"
  basis <- switch(ap$fun,
    Linear = sprintf("data.frame(f1 = %s)", f1),
    Quadratic = sprintf("{ f1 <- %s; data.frame(f1 = f1, f2 = f1^2) }", f1),
    Cubic = sprintf("{ f1 <- %s; data.frame(f1 = f1, f2 = f1^2, f3 = f1^3) }", f1),
    Logarithmic = {
      lx <- if (isTRUE(ap$all_positive)) "log(age)" else sprintf("log(age - %s + 1)", num(ap$min_age))
      sprintf("data.frame(f1 = %s)", if (isTRUE(ap$standardise)) sprintf("(%s - %s) / %s", lx, num(ap$mean_log), num(ap$sd_log)) else lx)
    },
    "Asymptotic exponential" = sprintf("data.frame(f1 = %s)", if (isTRUE(ap$standardise)) sprintf("(exp(-%s) - %s) / %s", zf, num(ap$mean_exp), num(ap$sd_exp)) else sprintf("exp(-%s)", zf)))
  fitted <- names(res$fits)
  covs <- res$covars %||% character(0)
  rterms <- res$random_terms %||% character(0)
  c("",
    "# ---------------------------------------------------------------------------",
    "# Figure: model predictions trajectory, with observed means and the decomposition",
    "# Predictions as in the app: random effects excluded; numeric covariates at their mean; factor covariates",
    "# averaged over the observed combinations of levels (weighted by individuals); ALR, AFR, LS and mean-age",
    "# terms at their individual-level means; response scale.",
    "# ---------------------------------------------------------------------------",
    "library(ggplot2)",
    paste0("make_basis <- function(age) ", basis, "  # the same age transformation as above"),
    paste0("fits <- list(", paste(sprintf("%s = %s", q(model_label(fitted)), tolower(fitted)), collapse = ", "), ")"),
    paste0("covariates <- c(", paste(q(covs), collapse = ", "), ")"),
    "population_curve <- function(fit, dat, ages) {",
    "  ind <- dat[!duplicated(dat$id), , drop = FALSE]",
    "  fac <- covariates[!vapply(ind[covariates], is.numeric, logical(1))]",
    "  numv <- setdiff(covariates, fac)",
    "  if (length(fac)) {",
    "    key <- do.call(paste, c(lapply(ind[fac], as.character), sep = \"\\r\"))",
    "    base <- ind[!duplicated(key), fac, drop = FALSE]",
    "    w <- as.numeric(table(key)[key[!duplicated(key)]])",
    "  } else {",
    "    base <- data.frame(.one = 1)",
    "    w <- 1",
    "  }",
    "  nd <- base[rep(seq_len(nrow(base)), times = length(ages)), , drop = FALSE]",
    "  nd$.w <- rep(w, times = length(ages))",
    "  nd$age <- rep(ages, each = nrow(base))",
    "  for (v in numv) nd[[v]] <- mean(ind[[v]], na.rm = TRUE)",
    "  b <- make_basis(nd$age)",
    "  for (nm in names(b)) {",
    "    nd[[nm]] <- b[[nm]]",
    "    mv <- if (paste0(\"mean_\", nm) %in% names(ind)) mean(ind[[paste0(\"mean_\", nm)]], na.rm = TRUE) else 0",
    "    nd[[paste0(\"mean_\", nm)]] <- mv",
    "    nd[[paste0(\"delta_\", nm)]] <- nd[[nm]] - mv",
    "  }",
    "  if (!is.null(nd$mean_f1)) { nd$mean_f1_2 <- nd$mean_f1^2; nd$mean_f1_3 <- nd$mean_f1^3 }",
    "  for (v in c(\"ALR\", \"AFR\", \"LS\")) {",
    "    val <- if (v %in% names(ind)) mean(ind[[v]], na.rm = TRUE) else 0",
    "    if (!is.finite(val)) val <- 0",
    "    nd[[v]] <- val; nd[[paste0(v, 2)]] <- val^2; nd[[paste0(v, 3)]] <- val^3",
    "  }",
    "  nd$id <- dat$id[[1]]",
    if (isTRUE(meta$has_group)) "  nd$group <- dat$group[[1]]" else NULL,
    if (isTRUE(meta$has_group2)) "  nd$group2 <- dat$group2[[1]]" else NULL,
    if (length(rterms)) paste0("  for (rt in c(", paste(q(rterms), collapse = ", "), ")) nd[[rt]] <- dat[[rt]][[1]]") else NULL,
    "  pr <- if (inherits(fit, \"nlme\")) {",
    "    predict(fit, newdata = nd, level = 0)",
    "  } else if (inherits(fit, \"glmmTMB\")) {",
    "    predict(fit, newdata = nd, re.form = NA, type = \"response\", allow.new.levels = TRUE)",
    "  } else {",
    "    predict(fit, newdata = nd, re.form = NA)",
    "  }",
    "  num_w <- tapply(as.numeric(pr) * nd$.w, nd$age, sum)",
    "  den_w <- tapply(nd$.w, nd$age, sum)",
    "  data.frame(age = as.numeric(names(num_w)), fitted = as.numeric(num_w / den_w))",
    "}",
    "ages <- sort(unique(dat$age))",
    "if (length(ages) > 30) ages <- seq(min(ages), max(ages), length.out = 80)",
    "curves <- do.call(rbind, lapply(names(fits), function(m) cbind(population_curve(fits[[m]], dat, ages), Model = m)))",
    "# observed means: mean over individuals of each individual's mean at that age",
    "ia <- aggregate(trait ~ id + age, data = dat, FUN = mean)",
    "ia$id <- as.character(ia$id)",
    "ia <- ia[order(ia$id, ia$age), ]",
    "observed <- aggregate(trait ~ age, data = ia, FUN = mean)",
    "observed$n <- as.numeric(table(ia$age)[as.character(observed$age)])",
    "# decomposition (Rebke et al. 2010): the app's own functions, copied here so that the figure matches the app",
    app_code_definitions(app_code_closure("decomposition_trajectory")),
    "decomp <- decomposition_trajectory(dat)",
    "ggplot() +",
    "  geom_point(data = observed, aes(age, trait, size = n), colour = \"grey40\", alpha = 0.5) +",
    "  geom_line(data = curves, aes(age, fitted, colour = Model), linewidth = 1.1) +",
    "  geom_line(data = decomp, aes(age, fitted), colour = \"purple\", linetype = 2, linewidth = 1.1) +",
    "  scale_size_area(max_size = 4, guide = \"none\") +",
    "  labs(x = \"Age\", y = \"Trait\", colour = NULL, subtitle = \"Points: observed means; dashed purple: decomposition\") +",
    "  theme_minimal(base_size = 13)")
}

model_r_code_nonlinear <- function(res, meta, source_label = "your_data.csv") {
  # build a copy explicitly: utils::modifyList() merges nested lists, so it would not empty fits or formulas
  r0 <- res
  r0$nonlinear <- FALSE
  r0$formulas <- list()
  r0$fits <- list()
  r0$basis <- "f1"
  r0$family <- "gaussian"
  r0$random_terms <- character(0)
  r0$among <- "linear"
  base <- model_r_code(r0, meta, source_label)
  base <- sub("library\\(lme4\\)", "library(nlme)", base)
  base <- sub("\nAIC\\(\\)$", "", base)
  lines <- strsplit(base, "\n", fixed = TRUE)[[1]]
  lines <- lines[!grepl("^dat <- dat\\[complete.cases", lines)]
  rand <- switch(res$random_structure %||% "none", correlated = "pdSymm(a + b ~ 1)", uncorrelated = "pdDiag(a + b ~ 1)", "pdSymm(a ~ 1)")
  grp <- if (isTRUE(meta$has_group2)) "~ group2 / group / id" else if (isTRUE(meta$has_group)) "~ group / id" else "~ id"
  rand_arg <- if (isTRUE(meta$has_group2)) {
    sprintf("list(group2 = pdSymm(a ~ 1), group = pdSymm(a ~ 1), id = %s)", rand)
  } else if (isTRUE(meta$has_group)) sprintf("list(group = pdSymm(a ~ 1), id = %s)", rand) else rand
  calls <- vapply(names(res$fits), function(m) {
    pa <- res$parts[[m]]$a
    pb <- res$parts[[m]]$b
    rhs <- function(x) if (length(x)) paste(x, collapse = " + ") else "1"
    sprintf("%s <- nlme(trait ~ a * exp(b * f1), data = dat, fixed = list(a ~ %s, b ~ %s), random = %s, groups = %s, start = c(%s), method = \"ML\", control = nlmeControl(returnObject = TRUE))",
            tolower(m), rhs(pa), rhs(pb), rand_arg, grp,
            paste(format(nlme::fixef(res$fits[[m]]), digits = 6), collapse = ", "))
  }, character(1))
  paste(c(lines, "# non-linear exponential models: trait = a * exp(b * z_age); starting values are the app's estimates",
          calls, paste0("AIC(", paste(tolower(names(res$fits)), collapse = ", "), ")"),
          if (length(res$fits)) plot_code_lines(res, meta) else NULL), collapse = "\n")
}

# ---------------------------------------------------------------------------
# Saved results: rendering and export
# ---------------------------------------------------------------------------
draw_saved_plot <- function(pl) {
  if (is.function(pl)) pl() else print(pl)
  invisible(NULL)
}

html_escape <- function(x) htmltools::htmlEscape(as.character(x))

table_to_html <- function(df, digits = 4) {
  if (is.null(df) || !is.data.frame(df) || !nrow(df)) return("")
  cell <- function(v) if (is.numeric(v)) format(signif(v, digits), trim = TRUE) else as.character(v)
  head <- paste0("<tr>", paste0("<th>", html_escape(names(df)), "</th>", collapse = ""), "</tr>")
  body <- vapply(seq_len(nrow(df)), function(i) {
    vals <- vapply(df, function(col) cell(col[i]), character(1))
    paste0("<tr>", paste0("<td>", html_escape(vals), "</td>", collapse = ""), "</tr>")
  }, character(1))
  paste0("<table>", head, paste(body, collapse = ""), "</table>")
}

plot_to_data_uri <- function(pl, width = 8, height = 5) {
  if (!requireNamespace("jsonlite", quietly = TRUE)) return(NULL)
  f <- tempfile(fileext = ".png")
  opened <- tryCatch({
    grDevices::png(f, width = width, height = height, units = "in", res = 110)
    TRUE
  }, error = function(e) FALSE)
  if (!opened) return(NULL)
  dev <- grDevices::dev.cur()
  ok <- tryCatch({
    draw_saved_plot(pl)
    TRUE
  }, error = function(e) FALSE)
  grDevices::dev.off(dev)
  if (!ok || !file.exists(f)) return(NULL)
  paste0("data:image/png;base64,", jsonlite::base64_enc(readBin(f, "raw", file.info(f)$size)))
}

html_report <- function(entries, heading = "disappR report", trait = "the trait") {
  css <- paste0("body{font-family:Helvetica,Arial,sans-serif;max-width:980px;margin:30px auto;color:#3d342d;line-height:1.5;padding:0 16px}",
                "h1{color:#5a4033}h2{color:#7b5a45;border-bottom:1px solid #e5d6c6;padding-bottom:4px;margin-top:34px}",
                ".meta{color:#8a7564;font-size:13px}table{border-collapse:collapse;margin:10px 0;font-size:13px}",
                "th,td{border:1px solid #e0d2c2;padding:4px 8px;text-align:left}th{background:#f4e8da}",
                "img{max-width:100%;margin:8px 0}pre{background:#2e2620;color:#f3e9dc;padding:12px;border-radius:8px;overflow:auto;font-size:12px}")
  parts <- c("<!DOCTYPE html><html><head><meta charset='utf-8'><title>disappR report</title><style>", css, "</style></head><body>",
             paste0("<h1>", html_escape(heading), "</h1>"),
             paste0("<p class='meta'>Generated ", html_escape(format(Sys.time(), "%Y-%m-%d %H:%M")), " with disappR ", DISAPPR_VERSION, "</p>"))
  if (!length(entries)) parts <- c(parts, "<p>No results were saved.</p>")
  entries <- report_order(entries)
  dl <- report_data_line(entries)
  if (!is.null(dl)) parts <- c(parts, paste0("<p class='meta'>", html_escape(dl), "</p>"))
  if (length(entries)) parts <- c(parts, evidence_report_html(entries, trait))
  for (e in entries) {
    parts <- c(parts, paste0("<h2>", html_escape(paste(e$section, "\u00b7", e$title)), "</h2>"))
    if (length(e$text)) parts <- c(parts, "<ul>", paste0("<li>", html_escape(e$text), "</li>"), "</ul>")
    tabs <- e$tables
    for (j in seq_along(tabs)) {
      cap <- names(tabs)[j]
      if (!is.null(cap) && !is.na(cap) && nzchar(cap)) parts <- c(parts, paste0("<p><b>", html_escape(cap), "</b></p>"))
      parts <- c(parts, table_to_html(tabs[[j]]))
    }
    for (pl in e$plots) {
      uri <- plot_to_data_uri(pl)
      if (!is.null(uri)) parts <- c(parts, paste0("<img src='", uri, "'/>"))
    }
    if (!is.null(e$code)) parts <- c(parts, paste0("<pre>", html_escape(e$code), "</pre>"))
  }
  c(parts, "</body></html>")
}

# The evidence summary for the report, as HTML or as plain lines: selective disappearance, and selective appearance
# when anything was saved for it. Built from the same graders as the app.
evidence_report_grades <- function(entries, trait) {
  g <- tryCatch(grade_evidence(entries, trait = trait), error = function(e) NULL)
  ga <- tryCatch(grade_appearance(entries, trait = trait), error = function(e) NULL)
  Filter(Negate(is.null), list(`Selective disappearance` = g, `Selective appearance` = ga))
}
footnote_of <- function(lines, i) {
  fn <- if ("Footnote" %in% names(lines)) lines$Footnote[[i]] else ""
  if (length(fn) && !is.na(fn) && nzchar(fn)) fn else ""
}
evidence_report_html <- function(entries, trait) {
  gs <- evidence_report_grades(entries, trait)
  if (!length(gs)) return(character(0))
  mark <- c(supports = "&#10003;", caveat = "!", contradicts = "&#10007;", `not saved` = "&ndash;")
  out <- "<h2>Evidence summary</h2>"
  for (nm in names(gs)) {
    g <- gs[[nm]]
    out <- c(out, paste0("<h3>", html_escape(nm), "</h3>"), paste0("<p><strong>", html_escape(g$headline), "</strong></p>"))
    if (!is.null(g$finding)) out <- c(out, paste0("<p><strong>Finding:</strong> the saved evidence suggests that ", html_escape(g$finding), ".</p>"))
    if (!is.null(g$explanation)) out <- c(out, paste0("<p>", html_escape(g$explanation), "</p>"))
    if (is.data.frame(g$lines) && nrow(g$lines)) {
      rows <- vapply(seq_len(nrow(g$lines)), function(i) {
        fn <- footnote_of(g$lines, i)
        paste0("<tr><td>", mark[[g$lines$Status[[i]]]], "</td><td><b>", html_escape(g$lines$Evidence[[i]]), "</b></td><td>",
               html_escape(g$lines$Note[[i]]), if (nzchar(fn)) paste0("<br><small>", html_escape(fn), "</small>") else "", "</td></tr>")
      }, character(1))
      out <- c(out, "<table>", rows, "</table>")
    }
    if (length(g$cautions)) out <- c(out, "<ul>", paste0("<li>", html_escape(g$cautions), "</li>"), "</ul>")
    if (length(g$pending)) out <- c(out, "<p><strong>Complete the following checks for more robust evidence:</strong></p><ol>",
                                    paste0("<li>", html_escape(unname(PENDING_TEXT[g$pending])), "</li>"), "</ol>")
  }
  out
}
evidence_report_text <- function(entries, trait) {
  gs <- evidence_report_grades(entries, trait)
  if (!length(gs)) return(character(0))
  mark <- c(supports = "[+]", caveat = "[!]", contradicts = "[x]", `not saved` = "[ ]")
  out <- "EVIDENCE SUMMARY"
  for (nm in names(gs)) {
    g <- gs[[nm]]
    out <- c(out, toupper(nm), g$headline)
    if (!is.null(g$finding)) out <- c(out, paste0("Finding: the saved evidence suggests that ", g$finding, "."))
    if (!is.null(g$explanation)) out <- c(out, g$explanation)
    if (is.data.frame(g$lines) && nrow(g$lines)) {
      out <- c(out, vapply(seq_len(nrow(g$lines)), function(i) {
        fn <- footnote_of(g$lines, i)
        paste(mark[[g$lines$Status[[i]]]], g$lines$Evidence[[i]], "-", g$lines$Note[[i]], if (nzchar(fn)) paste0("[", fn, "]") else "")
      }, character(1)))
    }
    if (length(g$cautions)) out <- c(out, paste("Note:", g$cautions))
    if (length(g$pending)) out <- c(out, "Complete the following checks for more robust evidence:",
                                    paste0(seq_along(g$pending), ". ", unname(PENDING_TEXT[g$pending])))
    out <- c(out, "")
  }
  out
}

# Saved results in the order they appear in the app (step, then top to bottom, left to right), and the data they
# were computed on, stated once rather than repeated under every result.
report_order <- function(entries) {
  if (!length(entries)) return(entries)
  ord <- vapply(entries, function(e) as.numeric(if (is.null(e$order)) 9999 else e$order), numeric(1))
  entries[order(ord, seq_along(entries))]
}
report_data_line <- function(entries) {
  d <- unique(vapply(entries, function(e) if (is.null(e$data)) "" else e$data, character(1)))
  d <- d[nzchar(d)]
  if (!length(d)) return(NULL)
  if (length(d) == 1) paste("Data analysed:", d) else paste("Data analysed (results were saved from more than one dataset):", paste(d, collapse = " | "))
}

text_report <- function(entries, heading = "disappR report", trait = "the trait") {
  lines <- c(heading, paste("Generated:", format(Sys.time())), "")
  if (!length(entries)) lines <- c(lines, "No results were saved.")
  entries <- report_order(entries)
  dl <- report_data_line(entries)
  if (!is.null(dl)) lines <- c(lines, dl, "")
  if (length(entries)) lines <- c(lines, evidence_report_text(entries, trait))
  for (e in entries) {
    lines <- c(lines, paste0("== ", e$section, " \u00b7 ", e$title, " =="))
    if (length(e$text)) lines <- c(lines, paste("-", e$text))
    tabs <- e$tables
    for (j in seq_along(tabs)) {
      cap <- names(tabs)[j]
      if (!is.null(cap) && !is.na(cap) && nzchar(cap)) lines <- c(lines, paste0("[", cap, "]"))
      lines <- c(lines, utils::capture.output(print(as.data.frame(tabs[[j]]), row.names = FALSE)))
    }
    if (length(e$plots)) lines <- c(lines, sprintf("(%d plot(s) included in the HTML report)", length(e$plots)))
    if (!is.null(e$code)) lines <- c(lines, e$code)
    lines <- c(lines, "")
  }
  lines
}

# ---- Moved unchanged from inst/app/server.R (0.9.11): pure helpers that use no reactive state ----

# ======================================================================
# R code for each section: current settings + the app's own functions
# ======================================================================
dput_text <- function(x) paste(deparse(x, width.cutoff = 500L), collapse = "\n")

script_header <- function(entries, packages = "ggplot2") {
  defs <- tryCatch(app_code_definitions(app_code_closure(entries)), error = function(e) paste("# helper functions could not be collected:", conditionMessage(e)))
  c("# disappR: R code for this section, generated with the current settings",
    paste0("# Created ", format(Sys.time(), "%Y-%m-%d %H:%M")),
    "# The helper functions are copied from disappR, so this script runs on its own.",
    paste0("library(", packages, ")"),
    "",
    "# ==== Helper functions from disappR (no need to edit) ====",
    defs,
    "# ==== End of helper functions ====",
    "")
}
