# disappR engine - User-interface helpers and help text for the Shiny app ('i' help entries, info titles, save buttons).
# Moved verbatim from inst/app/global.R (0.9.9); do not edit here without the golden tests (tests/golden/).

optional_packages_ui <- function(st = OPTIONAL_STATUS) {
  tags$table(class = "table table-condensed optional-pkgs", tags$tbody(lapply(seq_len(nrow(st)), function(i) {
    tags$tr(tags$td(strong(st$Package[[i]])),
            tags$td(if (isTRUE(st$Installed[[i]])) span(class = "pkg-ok", paste("\u2713", st$Version[[i]])) else span(class = "pkg-missing", "\u2717 not installed")),
            tags$td(st$Needed_for[[i]]))
  })))
}

# UI helpers shared by ui.R and server.R (objects defined in ui.R are not visible to the server)
sign_choices <- c("\u2212 (negative)" = "-1", "0 (none)" = "0", "+ (positive)" = "1")

box_note <- function(...) div(class = "small-note", ...)

# Columns usable for subsetting: text columns with 2-50 levels or numeric columns with 2-10 distinct values.
subset_candidates <- function(df) {
  if (is.null(df) || !ncol(df)) return(character(0))
  names(df)[vapply(df, function(x) {
    v <- x[!is.na(x)]
    if (!length(v)) return(FALSE)
    nu <- length(unique(v))
    num <- suppressWarnings(as.numeric(as.character(v)))
    if (mean(is.finite(num)) >= 0.95) nu >= 2 && nu <= 10 else nu >= 2 && nu <= 50
  }, logical(1))]
}

# ---------------------------------------------------------------------------
# "i" help content: what each section does, how to use and read it, and cautions
# ---------------------------------------------------------------------------
# An info panel. what/how/caution are the plain statement a user needs to use and read the output;
# `more` carries the mechanics, formulae and edge cases, shown only when the reader opens "More info".
info_entry <- function(title, what, how, caution, more = "")
  list(title = title, what = what, how = how, caution = caution, more = more)

INFO <- list(
  overview = c(info_entry("The workflow", "", "", ""),
    list(lead = "Follow tabs 1\u20136 to diagnose the dataset and interpret and quantify the pattern of ageing and selective processes. Click on SAVE TO SUMMARY for every result that you are happy with and wish to include in your manuscript: these are collected at the end in an HTML report, along with the associated R code to reproduce them.")),
  quickstart = info_entry("Quick start",
    "Loads a simulated teaching dataset (where the answer is known) or one of the bundled published datasets.",
    "Simulated data show textbook patterns with a known truth; the fly data are a real reanalysis with count data, covariates, nesting and censoring. Saved results are collected on the 'Summary and report' tab.",
    "Teaching simulations use deliberately strong effects."),
  data_source = info_entry("Data source and simulation",
    "Loads simulated data with a known answer, one of 13 empirical examples from 12 published studies, or your own CSV of longitudinal data on individuals sampled repeatedly across ages or time steps.",
    "With the simulator, change one setting at a time and see how the diagnostics and rankings respond. With an empirical example, the defaults follow the published analysis as closely as the app and each study\u0027s description of its methods allow.",
    "",
    more = "Simulated data (known truth), a bundled empirical example, or your own CSV with one row per individual \u00d7 age. The examples cover laboratory systems (fruit-fly and seed-beetle fecundity, leafcutting-bee activity) and wild populations (tern immunity and navigation, painted turtle reproduction, great tit recruitment, chipmunk reproduction, Soay sheep reproduction); each opens with the mapping, family and models set close to its published analysis. The simulator builds individual trajectories from a chosen ageing form (linear, quadratic, cubic, logarithmic, exponential) and a biologically motivated shape within it \u2014 slow, fast or no senescence, an early or late peak then senescence, decline then improvement, or a rapid or gradual change that levels off. Each form's default shape matches earlier versions. Selective disappearance can be absent, age-independent (lifespan linked to the individual's level), age-dependent (linked to its rate of ageing) or both, positive or negative; with individual-specific AFR, selective appearance is set the same way. Diet lowers the trait only; families add a nested random effect. Change one setting at a time and press 'Simulate & use this dataset'. Mean lifespan sets how many occasions each individual supplies. Use 'Subset the data' for one group (a sex or treatment). For your own CSV, age must be numeric (not classes or text); missing values can be blank or NA."),
  afr_expression = info_entry("Counting missed occasions: from AFR or from AFE",
    "Sets where each individual's expected-occasion window opens. 'Age at first record (AFR)' opens each individual's window at its first observation of the trait, so the first observation is never counted as missed. 'Age at first trait expression (AFE)' is the age from which the trait exists and could in principle have been measured, entered as one age that applies to every individual: body size is expressed from birth even if recording begins at first breeding.",
    "Use AFR when the trait genuinely begins when the individual enters the data (a first clutch, for example). Use AFE when individuals could have been measured earlier than they were, and give the age at which the trait starts.",
    "This setting changes the missingness figures only. It affects this tab's grid, missed-occasion counts and coverage; it does not enter any model, proxy or statistic anywhere in the app, all of which use AFR. Counting from AFE usually raises the estimated missingness, sometimes substantially, and changes its age profile at young ages, so the two definitions are not comparable: say which one you used when reporting."),
  afr_alr = info_entry("Agreement between AFR and ALR",
    "Correlation between each individual's age at first record and its age at last record, with the mean and SD of the observation window (ALR \u2212 AFR). The figure shows the dashed 1:1 line and the linear regression of ALR on AFR (solid black, with its 95% band).",
    "Under a fixed entry age, AFR does not vary and the correlation is undefined. A correlation near zero means entry and exit are independent, so ALR reflects lifespan rather than when an individual was first seen. A strong positive correlation means individuals that enter late also leave late, so the two proxies carry overlapping information and AFR terms (Models 7-10) and ALR terms (Models 2, 4) compete for the same variance.",
    "Missingness alters both AFR and ALR across individuals: a missed first occasion pushes AFR later, a missed final occasion pulls ALR earlier, so neither proxy is observed cleanly when sampling is incomplete. A high correlation can arise from biology (late starters live longer) or purely from the study design (a short study window forces late entrants to have late exits), and this diagnostic cannot separate the two. With few individuals the correlation is unstable. Mean age is affected by both ends of the window, so a variable AFR degrades it as a proxy of lifespan more than it degrades ALR."),
  among_order = info_entry("Higher-order among term",
    "Controls how the among-individual terms enter when the ageing function is quadratic or cubic. Linear is the default and matches the manuscript: mean age, ALR, LS and AFR each enter once.",
    "Use a higher-order term when you expect the among-individual effect itself to be curved \u2014 for example when mid-lived individuals differ from both the shortest- and the longest-lived, which a single linear term cannot show. 'Consistent decomposition' is the option to use for the centring models: it adds the individual mean of age\u00b2, which pairs exactly with the within-individual \u0394(age\u00b2) term so that the two reconstruct age\u00b2.",
    "'Powers of the mean' squares the mean age instead. That mirrors ALR + ALR\u00b2 and is fine for the ALR, LS and AFR models, but in the centring models it does not pair with \u0394(age\u00b2): the two differ by the within-individual spread of sampled ages, which is larger in individuals observed longer. Higher-order terms also cost degrees of freedom and need enough distinct ages per individual to be estimable.",
    more = "For a quadratic basis the age term splits as age\u00b2 = mean_i(age\u00b2) + [age\u00b2 \u2212 mean_i(age\u00b2)]. The second part is the within-individual term the app always uses (delta_f2). 'Consistent decomposition' supplies the first part, so among + within reconstructs age\u00b2 exactly. 'Powers of the mean' supplies (mean age)\u00b2 instead, and mean_i(age\u00b2) \u2212 (mean age)\u00b2 = Var_i(age), so a term correlated with how long each individual was observed is left out of the model. The two options coincide only when every individual is observed at exactly the same set of ages, when Var_i(age) is constant and the intercept absorbs it. That is rarer than it sounds: even with complete sampling from age one, individuals differ in lifespan, so Var_i(age) still varies and correlates about 0.98 with age at last record."),
  duplicates = info_entry("Repeated ID \u00d7 age records",
    "What to do when the same individual appears more than once at the same age. 'Keep all' (the default) keeps every row. 'Collapse exact duplicates' keeps one row where the repeated rows agree in every mapped column - the same record entered twice.",
    "Rows that differ in anything - the trait, the number of trials, a covariate, the condition, the group - are two measurements, not a duplicate, and are always kept whichever option you choose. The data checks name the individuals and ages involved and say which columns differ, so you can decide: fix a typo in the ID or age, map the grouping column if the same ID is reused in different families, vials or sites, or combine the rows yourself in the way that suits the trait.",
    "Nothing is averaged for you. Averaging a repeated measure would invent values - a mean proportion beside a number of trials it never came from, or one trait's value merged with another measured at the same age."),
  mapping = info_entry("Map columns",
    "Tells the app which columns are the individual, the age and the trait, and optionally lifespan, entry age, covariates and extra random effects.",
    "The three required columns must be different. Age must be numeric. Map lifespan when you know it: it makes Model 6 available as a benchmark.",
    "Getting this wrong invalidates everything downstream. Non-numeric values in a continuous covariate are treated as missing and drop those rows.",
    more = "Tells the app which columns hold ID, age and trait, plus optional ALR, lifespan, AFR (age at first observation), continuous and categorical fixed-effect covariates, their interactions, grouping, additional random intercepts, censoring and an optional age resolution. Uploaded columns keep their names. Continuous covariates (e.g. temperature) enter the models as linear effects; categorical covariates (e.g. treatment, sex, diet) enter as factors with one coefficient per level. Interactions can be a covariate \u00d7 age (the covariate changes the shape of the ageing trajectory, e.g. diet \u00d7 (age + age\u00b2)) or between two covariates (e.g. diet \u00d7 sex, added to every model with both main effects). Covariates and interactions are used in the mixed models on tab 5 (Modelling). Map lifespan (LS) only if it is truly known; use nesting when IDs repeat across groups; map a censoring column for individuals alive at the end of the study. With a 'next level up' column the random effects have three levels, e.g. individuals within fathers within families: (1 | family) + (1 | family:father) + (1 | family:father:ID)."),
  subset = info_entry("Subset the data",
    "Restricts every analysis to the rows whose value of one categorical variable (a text column with up to 50 levels, or a numeric column with up to 10 distinct values) is among the chosen levels.",
    "Pick the variable, then tick the levels to keep (for example females only, or one treatment). Leave the variable empty to use all rows. The subset applies to the integrity checks, all diagnostics, individual fits and models, and to the exported R code only through the data you supply.",
    ""),
  integrity = info_entry("Data integrity checks",
    "Checks the data for duplicate records, ages that look like calendar years, individuals seen only once, infinite values and other recording problems.",
    "Clear anything flagged here before modelling. The suggested error family is a starting point, not a decision.",
    "These checks cannot find every recording error. Infinite values are kept and can still be mapped, but they distort every summary they enter.",
    more = "Flags problems that change results: duplicate records, IDs in several groups, missing or impossible lifespans, censoring, the sampling schedule (step, off-schedule rows, staggered or irregular schedules), few records per individual, AFR variation, AFR\u2013ALR correlation, missing-value codes (-99, -999, -9999), ages at or below zero, covariates without variation, with many levels or with missing values, empty columns, extreme trait values and the trait distribution. 'Warning' rows need action (fix the data or the mapping); 'Note' rows are informative. The sampling step is the most common interval between an individual's consecutive records, so staggered cohorts and floating-point ages are handled."),
  distribution = info_entry("Distribution of a variable",
    "Histogram (numbers) or bar chart (categories) of any column, per row or per individual.",
    "Look for skew, zeros, outliers and unexpected categories before choosing an error family or covariates.",
    "It shows the data as loaded (after any subset on the Data tab): the observed records only. For simulated data these are the records left after the simulated missingness has removed missed occasions, with no records after death, not the complete simulated population. 'Per individual' averages the raw ID column, so individuals nested in groups with repeated IDs are merged here."),
  visual_settings = info_entry("Set the number of bins and the selection term of interest",
    "The bins set here determine how the plots that diagnose selective processes are stratified. Choose the grouping variable, the number of bins, the panels and the trait scale.",
    "Choose ALR, mean age or LS for selective disappearance, AFR for selective appearance. By default the number of bins is half the average number of time steps per individual, within what the data allow. Fewer bins put more individuals behind each point and give a steadier pattern; more bins resolve it more finely, with fewer individuals per point.",
    "Every bin and age point needs at least three individuals, so sparse bins are not drawn.",
    more = "The variable that groups individuals (ALR, mean age, LS or AFR), the number of bins, panels and the trait scale, applied to both lifespan-group figures. Settings that affect a single figure sit just above that figure. The grouping variable forms the bins of the trajectory plot and the x-axis of the lifespan plot; the number of bins sets the number of groups in the trajectory plot and of age bins in the lifespan plot. Choose ALR, mean age or LS to diagnose selective disappearance and AFR to diagnose selective appearance. Every bin \u00d7 age point in the trajectory plot and every age bin in the lifespan plot needs at least 3 individuals, so sparse bins are not drawn. With no more distinct values than bins, each value is its own bin, and the same bin boundaries are used in every panel. Increase the number of bins to resolve finer differences, but not so far that a bin holds too few individuals: a useful starting point is the number of time steps divided by three. Few bins hide patterns, many bins give noisy points. Facets split the sample, so each panel has fewer individuals. A time-varying covariate is summarised by each individual's most common value. On the log scale, differences are ratios."),
  a1 = info_entry("Trajectories within bins",
    "Groups individuals by how long they were observed, then plots mean trait against age for each group. Grey open circles are the observed mean of the trait at each age across every individual, sized by the number of individuals and on the same scale as the bins (raw or log(trait + 1)), so the bins can be read against the data behind them.",
    "Parallel bands indicate a constant difference between groups. Bands that separate or converge with age indicate an age-dependent difference. Overlapping bands indicate no difference. Switch to AFR groups for selective appearance.",
    "Few individuals contribute at older ages, so late points are imprecise. Bands can overlap by chance while selection is still present. Non-linear lifespan effects are not shown here. Use the trait scale suggested above the figures (raw for continuous traits, log(trait + 1) for counts): on the wrong scale the differences between groups can shrink, vanish or even reverse.",
    more = "Mean trait at each age for individuals grouped into bins of ALR, LS, mean age or AFR (each individual counted once), optionally in separate panels per covariate level. Points need at least 3 individuals. The bin boundaries (quantiles by default, so each bin holds about the same number of individuals; equal width can be chosen instead, at the cost of sparse outer bins; when many individuals share the same lifespan, some quantile boundaries coincide and fewer bins are formed), \u00b11 SE and the panels of this figure (any categorical variable, or as in the settings above) are set above the figure; the bin differences below use the same panels. The manuscript sets out several manifestations of selective disappearance: selection gradients that change with age, early- versus late-life trade-offs and pace-of-life differences among individuals, a weakening of selection, terminal investment, and survival costs of a trait that depend on condition and shift with age. The figures here let you evaluate each of these qualitatively. Overlapping bins: consistent with and indicative of no selective disappearance. Parallel but offset bins: consistent with and indicative of age-independent selection. Bins that diverge or converge with age: consistent with and indicative of age-dependent selection. Use AFR bins for selective appearance, and compare panels to see whether the pattern differs between treatments. See the figure beside this one for a quantification of the bin differences. At older lifespans, fewer individuals contribute to a bin, so those points are less accurate. Beware of false negatives: bins may differ only stochastically when you look at them, yet still sit on top of real selective processes. Non-linear trajectories are not plotted here."),
  a1_diff = info_entry("How big is the gap between lifespan groups at each age?",
    "Plots the gap between neighbouring lifespan groups at each age, which quantifies what the trajectory figure shows.",
    "A flat series indicates an age-independent difference. A series with a trend indicates an age-dependent one. Tick 'Inverse-variance weights' to weight each difference by the inverse of its variance (the sum of the squared standard errors of the two bin means), so that differences estimated precisely count more in the trend lines than those resting on few or variable individuals. Untick 'Show individual points' to see only the trend lines.",
    "Each point rests on two bins, so it is noisier than the trajectory figure. Late ages rest on few individuals. Use the trait scale suggested above the figures (raw for continuous traits, log(trait + 1) for counts): on the wrong scale the differences between groups can shrink, vanish or even reverse.",
    more = "Signed difference in mean trait between consecutive bins (higher bin minus the next lower bin) at each age, with least-squares trend lines of difference against age: one line per bin pair, or a single line pooling all pairs (chosen above the figure), each with its 95% confidence band (shaded). Differences near zero with flat lines: no selection. Constant non-zero differences (flat lines away from zero): age-independent selection. Lines that rise or fall: age-dependent selection. The single pooled line answers 'do neighbouring lifespan bins become more (or less) different with age on average?'; separate lines show whether particular bins drive the pattern, for example only the longest-lived bin diverging at late ages. The saved table reports each line's slope per unit age. A point appears only where both bins have at least 3 individuals; differences at late ages rest on few individuals. The pooled line does not weight points by sample size, so treat its slope as descriptive. The confidence bands come from the same unweighted least-squares fits (each plotted difference counts as one point), so they are descriptive too; a line through only two points has no band."),
  a2 = info_entry("Does the trait track lifespan, and does that change with age?",
    "Plots the trait against the lifespan proxy separately within each age bin.",
    "A slope that is similar in every age bin indicates an age-independent association. A slope that changes across age bins indicates an age-dependent one. The caption under the figure gives the slope in each age bin, its change from the previous bin, and whether the slope changes with age (a trend weighted by the inverse variance of each slope, with its p-value).",
    "For count traits the slope can change through scale alone, so compare against the log scale before concluding. Use the trait scale suggested above the figures (raw for continuous traits, log(trait + 1) for counts): on the wrong scale the differences between groups can shrink, vanish or even reverse.",
    more = "Each individual's mean trait within an age bin, plotted against its lifespan (or ALR / AFR), with a straight-line fit and its 95% confidence band per age bin; age bins need at least 3 individuals. The caption lists the regression coefficient (slope) in each age bin and its change from the previous bin, and tests the trend of the coefficient across age by weighted least squares, each coefficient weighted by the inverse of its squared standard error. Saving the figure also stores each coefficient's 95% CI, the correlation r and its p-value. Coefficients near zero in every bin: no selection. Similar non-zero coefficients in every bin: age-independent selection. Coefficients that change across consecutive age bins: age-dependent selection. Untick 'Show individual points' above the figure to see only the fitted lines, which makes differences in slope between age bins easier to judge. Older age bins contain only long-lived individuals, so their lifespan range is narrow and coefficients are imprecise (wide CIs). When count means and variances fall with age, coefficients can change through scale alone: compare with the log scale or r. The age-specific coefficients share individuals, so the trend across ages treats correlated estimates as independent."),
  a5_terminal = info_entry("Do individuals change in their final occasions?",
    "Aligns individuals on occasions before death rather than on age, and plots the mean trait for the shortest-, middle- and longest-lived thirds.",
    "A fall or rise in the final occasions indicates that individuals change as they approach death, separately from chronological ageing. A change of similar size in every lifespan group suggests age-independent selective disappearance; one larger in a particular group suggests it depends on age.",
    "A terminal-investment process can resemble or show up as selective disappearance. Consider which interpretation is biologically more plausible for your system, and use the other diagnostics and the modelling steps to decide. Use the trait scale suggested above the figures (raw for continuous traits, log(trait + 1) for counts): on the wrong scale the differences between groups can shrink, vanish or even reverse.",
    more = "Mean trait against occasions before death (known lifespan; 0 = the last occasion) or before the last record, for the shortest-, middle- and longest-lived thirds. Aligning individuals on time before death separates changes linked to approaching death from chronological ageing. A drop (terminal decline) or rise (terminal investment) in the final occasions means dying individuals show a distinct investment in their phenotype as their residual reproductive value changes. Short-lived individuals reach their final occasions young and long-lived ones old, so the same terminal change removes distinct individuals at different ages: a terminal change of similar size in every lifespan group might indicate age-independent selective disappearance; one that is larger in a particular group might indicate that its strength depends on age."),
  a6_selection = info_entry("Do survivors differ from those that disappear?",
    "At each age, compares the mean trait of individuals that survive to the next occasion against those that do not.",
    "A point whose interval excludes zero indicates selective disappearance at that age. A trend across age indicates that its strength depends on age.",
    "These describe selection on the observed trait, not its cause. Ages with few survivors or few disappearances are dropped. Use the trait scale suggested above the figures (raw for continuous traits, log(trait + 1) for counts): on the wrong scale the differences between groups can shrink, vanish or even reverse.",
    more = "At each age, the difference in mean trait between the individuals that survive to their next occasion and all individuals present (the selection differential), or between survivors and those that disappear, in within-age SD units, with 95% intervals and a weighted trend across age. Compare the mean trait of individuals that survive against those that die (or against the whole population). If these differ \u2014 that is, the point and its interval do not overlap zero \u2014 this might indicate selective disappearance at that age. If the difference between them changes with age, this might indicate age-dependent selective disappearance."),
  a7_hazard = info_entry("Disappearance hazard",
    "Shows the probability of disappearing before the next occasion at each age, against the overall age-independent rate (dashed line).",
    "Points above the line mark ages where individuals disappear faster than average, points below where they disappear more slowly. A rising series indicates actuarial senescence, so later ages are thinned most and selection acts hardest there. A falling series means early losses dominate.",
    "With unknown lifespan, disappearance includes missed detection and emigration. Old ages rest on few individuals, so intervals are wide.",
    more = "At each age, the probability of disappearing before the next occasion (with 95% Wilson intervals, point size = individuals at risk), the overall, age-independent hazard (dashed line: all disappearances / all individual-occasions at risk), and a likelihood-ratio test of a constant hazard against age-specific hazards. The dashed line is the overall hazard: the share of all individual-occasions that ended in disappearance, ignoring age. Points above it mark ages where individuals disappear faster than average, points below it ages where they disappear more slowly. A flat series along the dashed line is consistent with and indicative of a chance of disappearing that does not change with age. A series rising across age is consistent with and indicative of actuarial senescence, and means later ages are thinned most, so any selective disappearance acts hardest there. A falling series means the opposite: early losses dominate, and the survivors reaching old age are already a filtered set. With unknown lifespan, disappearances include missed detections and emigration, and individuals alive at the study end must be marked as censored. Hazards at old ages rest on few individuals (wide intervals). The hazard is fitted with ordinary binomial GLMs on individual \u00d7 occasion records: the discrete-time likelihood is standard, but unmodelled differences in frailty between individuals are not accounted for."),
  sampling_guidance = info_entry("Sampling summary and proxy guidance",
    "Summarises detection and proxy quality to guide the choice between ALR (Models 2, 4) and mean age (Models 3, 5). Missed occasions are counted only between each individual's first observation of the trait and its ALR, or from the age at first expression when that option is chosen.",
    "Read the guidance alongside the proxy-agreement plots. In the sampling grid, ordering by ALR or AFR uses the ALR and AFR the models use, which for simulated data are taken after missingness.",
    "In the manuscript we use 'missingness' for two things: occasions missed between AFR and ALR, and the occasions between ALR and true lifespan, at which an individual was alive but no longer recorded. Only the first is calculable from data alone, because the steps between ALR and LS are latent whenever lifespan is unknown. This grid therefore measures missingness between each individual's first and last record, so occasions missed after the last record are invisible to it and the detection rate reported here is an upper bound. The missingness grid assumes regular, scheduled sampling occasions: it is most reliable when every individual is due to be sampled at a common interval. With irregular ages (for example ages calculated from dates) expected occasions are approximate, so missingness percentages, patterns and drivers should be read qualitatively; round ages to a sampling resolution on the Data tab. Without known lifespan, occasions missed after the last record are invisible, so detection is overestimated. If individuals genuinely follow different schedules (for example some sampled every year and others every third year), the common step is the shortest one and the less frequently sampled individuals appear here as heavily missing: that is study design, not failed detection."),
  heatmap = info_entry("Sampling grid",
    "Draws one row per individual showing the ages at which it was recorded, so the sampling design is visible directly.",
    "Look for individuals with gaps, late entry or early exit, and for whole occasions missing across the population. Ordering by ALR or AFR uses the values the models use - the last and first recorded ages, with or without a trait value, or the mapped columns - so the latest ALRs sit at the bottom. Each row runs from the first observation of the trait to the ALR, which is marked: nothing before the first observation or after the ALR is counted as missed, whether or not lifespan is known. Individuals never measured for the trait enter no model and are not shown.",
    "With many individuals only a sample of rows is drawn.",
    more = "One row per individual and one column per expected occasion: observed, missed (expected but not recorded), the final expected occasion (death if LS is known, otherwise ALR), and white cells where no observations are expected (before AFR, after death or ALR). Each individual's schedule starts from its own first record (or the common start age), so staggered cohorts are not given spurious missed occasions. Scattered red cells: random gaps. Red concentrated at young or old ages: age-dependent sampling. Order rows by ALR, AFR, mean trait, ID or at random to see whether gaps line up with lifespan, entry age or trait values. Up to 500 individuals (set with 'Individuals to show in the grid') and 60,000 cells are drawn, evenly spaced in the chosen order. With irregular ages the occasions are approximate; round ages on the Data tab. Very fine or irregular ages are coarsened so that the grid stays below 300,000 cells, which is reported on this tab."),
  missing_by_age = info_entry("How much is missing, and where?",
    "Shows how many individuals are still present at each age and what share of expected occasions carry a trait record.",
    "Use it to see where the data thin out, and how far conclusions about old ages rest on few individuals.",
    "",
    more = "Individuals observed at each age (bars) and the percentage of expected occasions missed (line), with a table. Missingness rising with age suggests 'missing when old'; high early missingness suggests 'missing when young'. Percentages at the oldest ages rest on few individuals."),
  missing_vs_var = info_entry("Is what is missing related to the trait or the individual?",
    "Tests whether missing records are related to age, lifespan, entry age, condition or the previous trait value.",
    "Use this to judge whether missingness looks random, or whether older, younger, longer-lived or higher-trait individuals go missing more often.",
    "These are associations, not tests of the type of missingness. Missingness that depends on the trait produces the same evidence as age-dependent selective disappearance, and no model on these data can separate the two.",
    more = "Missed-occasion rate against an individual-level variable, and logistic regressions of missingness on age, LS, AFR, the previous trait value and condition. Use this to judge whether missingness might be random, or whether the pattern is indicative of non-random missingness \u2014 older, younger, longer-lived or higher-trait individuals going missing more often. These are only associations, so use them as suggestions rather than as anything definite. Do not use visual diagnostics of missingness as quantitative tests of the type of missingness."),
  proxy_agreement = info_entry("ALR, mean age and lifespan",
    "Compares the lifespan proxies against each other, and against known lifespan where you have it.",
    "A proxy that tracks lifespan closely corrects better for which individuals remain. Under incomplete sampling or variable entry age, age at last record tracks lifespan better than mean age.",
    "",
    more = "ALR is the age at an individual's last record in the data. It equals lifespan only when individuals are followed until death: emigration, missed detection and censoring also end the records, so ALR is a proxy of lifespan. Pairwise agreement between ALR, mean sampled age and known lifespan (one point per individual, with r, a dotted 1:1 line and a solid black linear regression line). High r(ALR, LS) supports ALR-based models (2, 4); high r(mean age, LS) supports centring models (3, 5). Under complete sampling ALR and mean age are nearly interchangeable. The regression line shows how one measure scales with the other: departures from the 1:1 line reveal systematic under- or overestimation, for example ALR falling increasingly short of lifespan when final occasions are missed. Missed final occasions make ALR underestimate lifespan; intermittent gaps shift mean age. With unknown lifespan only ALR vs mean age is shown."),
  a3_settings = info_entry("Which function best describes individual-level data?",
    "Explores which ageing function might best describe the average trajectory of the individuals in your data, by fitting the same function to each individual in turn.",
    "Fit a function, press 'Compare ageing functions across individuals' to compare the functions in the table, then send the one you choose to the modelling step.",
    "A misspecified ageing function can lead to incorrect conclusions about selective disappearance. Individuals need more records than the function has parameters.",
    more = "Scale: count traits are fitted on the log scale (a Poisson fit for each individual), the scale on which they are modelled and simulated; 'Automatic' decides from the trait. Minimum records: with noisy traits and higher-order functions, individuals with few records dominate the average, so raise it to fit only well-sampled individuals - at the cost of fitting longer-lived individuals, which the survivor-bias check below reports. How does each individual age? This fits each individual\u0027s longitudinal data with the same ageing function, for example logarithmic or quadratic. You can then compare, below, how much of the variation in the individual data each functional form explains, and judge at the individual level which function each individual might be ageing along. Averaging the fitted functions, or averaging their coefficients, reconstructs the approximate parametric latent function that represents the average within-individual trajectory. Compare functions in the table. 'Use this ageing function for the mixed models' makes the selected function the ageing function on the Modelling tab (otherwise, once you have run the comparison, the Modelling tab starts with the function with the lowest mean \u0394AICc across individuals). 'Exponential (a \u00b7 exp(b \u00b7 age))' is fitted by non-linear least squares and is the only function that is non-linear in its parameters. Draw the longest- or shortest-lived individuals to see how fits change with the number of records. Individuals need at least 2 records at different ages for a linear fit, 3 for quadratic, logarithmic and exponential fits, and 4 for a cubic fit. With exactly as many records as parameters the curve passes through every point, so it carries no residual information (no AICc) and is left out of the function comparison. Non-linear fits that do not converge are dropped."),
  a3_scale = info_entry("Scale of the individual fits",
    "Sets the scale on which each individual's ageing function is fitted. 'Raw trait' fits the function to the trait as recorded, by least squares: for continuous traits, for example body mass. 'Log (counts)' fits it to the log of the expected count, with a Poisson likelihood for each individual: for counts, for example fecundity. 'Automatic' chooses the log scale for counts and the raw scale otherwise.",
    "The curves are always drawn in the trait's own units, so on the log scale the chosen function is straight or curved on the log scale, not in the figure. A Linear function on the log scale is log(expected count) = b0 + b1\u00b7age, so the expected count is exp(b0 + b1\u00b7age): a curve that is always positive and changes by the same percentage per unit age. It is not a quadratic; a Quadratic on the log scale is exp(b0 + b1\u00b7age + b2\u00b7age\u00b2). Use the log scale for counts - they cannot be negative, their variance grows with the mean, and the mixed models for counts use a log link, so the individual fits then match the scale of the models. Use the raw scale for continuous traits.",
    "Counts fitted on the raw scale can be given negative expected values, and individuals with high counts dominate. The log scale needs non-negative traits; with negative values the fits use the raw scale. The shape you choose describes the trait on the scale it is fitted on, so compare functions on the same scale as the mixed models you will fit."),
  a3_fits = info_entry("Individual trajectories and data support",
    "Fits each individual's own ageing curve with the function you choose, and draws a sample of them against that individual's records.",
    "Look at how consistently individuals follow the chosen shape, and whether this changes when longer- or shorter-lived individuals are plotted. Use the function comparison beside this figure to choose a different shape.",
    "This is a visual diagnostic, not a test. Individuals with few records are fitted loosely or not at all, so the sample you see is biased towards well-sampled individuals.",
    more = "Each panel shows one individual's records and fitted function, with free axes. The support metrics above summarise how much information there is to estimate individual ageing slopes: individuals, total trait observations, median and interquartile range of observations per individual, the percentage of individuals with at least 2, 3 and 4 time points (distinct ages), the number of distinct ages and the median age span per individual. Look for systematic misfit, for example curvature that a straight line misses. A straight line can be fitted to 2 time points, but it passes through both exactly; slopes that can be separated from residual noise need at least 3 time points, and a quadratic fit that is not exact needs 4 or more. With few records the fit is nearly exact and says little about the true shape. If few individuals have \u2265 3 time points, individual slopes (individual fits) and random slopes (Models tab) are poorly estimated. A quadratic fitted to 3 records, or a cubic to 4, interpolates them exactly (no residual degrees of freedom): the curve is drawn but says nothing about how well that function describes the individual."),
  a3_mean = info_entry("What is the average within-individual trajectory?",
    "Averages the fitted individual ageing trajectories, including every individual\u0027s trajectory across all sampled ages. This gives a parametric approximation of the latent average within-individual ageing trajectory that ecologists usually want to estimate (see the cautions for when this is inaccurate).",
    "Read it as the latent within-individual trajectory the analysis is trying to recover, and compare it with the model predictions on the Modelling tab. The two curves are identical only when the function is linear in its coefficients on the scale drawn (polynomials on the raw scale); on the log scale every function is drawn as exp(b0 + b1\u00b7age + ...), so the mean of coefficients traces the typical individual while the mean of individual curves traces the population average, which lies above it and is pulled up by individuals with extreme curves. Untick 'Show the mean of individual curves' to draw the typical individual alone. A large gap between them means the individual curves vary a lot - often because a flexible function fitted to few records (for example a cubic through four points) swings between ages - so read neither curve closely: raise the minimum records or choose a simpler function.",
    "It assumes individuals are immortal: each curve is extended past the ages at which that individual was seen, up to the oldest age in the dataset at which at least five individuals were recorded. It is unreliable with high missingness, few records per individual, small samples, or when individual ageing cannot be described by the same functional form. For count traits fitted on the log scale the two averages differ: the curve of the mean coefficients describes the typical individual, which is what the simulated truth shows, while the mean of the individual curves is the population average and lies above it where individuals differ.",
    more = "Averages the individual-level trajectories to reconstruct a population-level trajectory. The average is done in two ways, from the individual fits f(age; \u03b8\u1d62), i = 1\u2026N. Mean of coefficients: f(age; \u03b8\u0304) with \u03b8\u0304 = (1/N) \u03a3\u1d62 \u03b8\u1d62. Mean of functions: f\u0304(age) = (1/N) \u03a3\u1d62 f(age; \u03b8\u1d62). When f is linear in its parameters on the scale drawn the two are identical (the polynomial, logarithmic and asymptotic-exponential functions fitted on the raw scale); fitted on the log scale, every function is drawn as exp(f), which is non-linear in \u03b8, so the two differ. When f is non-linear in \u03b8 (e.g. a\u00b7exp(b\u00b7age)) they differ by Jensen's inequality: f(age; \u03b8\u0304) is the trajectory of the average individual, f\u0304(age) the average trajectory of the population. Bands: 95% intervals from SD\u1d62[f(age; \u03b8\u1d62)]/\u221aN (functions) and the delta method with Cov(\u03b8\u1d62)/N (coefficients). This tells you what the average within-individual ageing trajectory looks like when mortality is left out of account, and when each individual\u0027s parametric trajectory is extended to the last age even beyond that individual\u0027s death. Unlike observed means, averaged within-individual fits are not shifted by who survives: without selective disappearance the band should cover the true trajectory. The analysis tab can compare this reconstruction against the model predictions. For non-linear functions, choose the estimand: the average individual (coefficients, comparable to a GLMM's fixed-effect curve on the link scale) or the population average (functions, comparable to observed means when there is no selection). Treat this only as a suggestion of what the latent, true, average within-individual trajectory might look like if selective disappearance and appearance did not exist. The reconstruction assumes individuals are immortal, and that their functions behave the same way after death as they do while the individual is alive \u2014 each individual function is extended beyond the ages at which that individual was seen. It is inaccurate under missingness, with few sampled time steps or small samples, and when individuals have highly stochastic patterns or genuinely different functional forms."),
  a3_compare = info_entry("Individual-level function comparison",
    "Compares how well each ageing function fits individual trajectories, using mean adjusted R2 and mean dAICc across individuals.",
    "The function with the lowest mean \u0394AICc, or with the highest mean adjusted R\u00b2, can be inferred as the function with most support at the individual level.",
    "Unreliable with few records per individual, few sampling occasions, high missingness or small samples. Functions needing more records are fitted to fewer individuals, and dAICc uses only the individuals every function could be fitted to; if that set is much smaller than your sample, do not use the comparison. A function can fit well and still be biologically implausible. When N_common is low, the mean adjusted R\u00b2 may be more informative than \u0394AICc, because each function's mean uses every individual that function can be fitted to - though those sets differ between functions.",
    more = "Fit of each function to individuals, including the non-linear exponential: mean R\u00b2, adjusted R\u00b2, and mean \u0394AICc over individuals for which every function is estimable. The lowest mean \u0394AICc (and highest adjusted R\u00b2) indicates the function with most support at the individual level. Treat the ranking as suggestive, not prescriptive: it describes which function is estimable from these individuals, not which function generated the data, and a difference of a few AICc units is not evidence for one shape over another. Functions that need more records can only be fitted to the individuals that have enough data, which makes their AICc rest on a different, easier set of individuals. The \u0394AICc column therefore uses only the individuals for which every function is estimable (N_common). If that common set is substantially smaller than the total sample, the AICc comparison is inaccurate and should not be used. For the function used in the models, the Ageing-function check in step 5 is more reliable than this comparison. When sampling intervals are few, the best-fitting individual-level function is often not the generating equation, even in simulations where that equation is known: with few points per individual the exact function cannot be drawn precisely, so these AIC values are suggestive rather than true. Beware of false positives: a function can have statistical support and still be biologically implausible. Fitting functions at the individual level needs many time steps and a large enough sample, and assumes every individual follows the same functional form and differs only in the coefficients \u2014 which may not hold, for instance if ageing is stochastic or cannot be described by a function at all. Beware of AIC comparison: these are not quantitative tests, only suggestions."),
  a3_coefs = info_entry("Individual coefficients",
    "Summarises the coefficients estimated for each individual under the chosen ageing function: their mean (the coefficient averaged across individuals), variability (heterogeneity among individuals in that coefficient) and range across individuals.",
    "The functions fitted are: Linear, b0 + b1\u00b7age, where b0 is the intercept and b1 the linear rate of change with age. Quadratic, b0 + b1\u00b7age + b2\u00b7age\u00b2, where b2 is the curvature: negative for a rise-then-fall, positive for a fall-then-rise. Cubic, b0 + b1\u00b7age + b2\u00b7age\u00b2 + b3\u00b7age\u00b3, where b3 allows a second change of direction. Logarithmic, b0 + b1\u00b7log(age), where b1 is the change per proportional increase in age, so change slows as age rises. Asymptotic exponential, b0 + b1\u00b7exp(\u2212z), where z is age standardised to mean zero and unit standard deviation. b0 is the level approached at old age and b1 sets how far from that level the trait starts; the rate of approach is fixed by the spread of ages, not estimated.",
    "Wide spread in a coefficient means individuals differ in that aspect of ageing. Coefficients are estimated on standardised age unless standardisation is switched off, so compare them within one analysis rather than across datasets. For count traits fitted on the log scale, the coefficients are on the log scale: exp(b0) is the expected count at age zero, and each coefficient changes the log of the expected count."),
  b2 = info_entry("Which shape fits the population trajectory?",
    "Fits each ageing function to the whole population rather than to individuals, and compares the resulting curves and AICs.",
    "Compare with the individual-level comparison: that one asks which shape describes individuals, this one which shape describes the population trajectory.",
    "This fit carries no lifespan or entry-age term, so the preferred shape can change once you add them. Cubic curves extrapolate poorly.",
    more = "Evaluated at the population level rather than per individual: the functional form of each ageing function is fitted directly to the data by restricted maximum likelihood as a mixed model (the non-linear exponential by non-linear least squares), using the error family, covariates and random effects chosen on the Modelling tab, and the AICs and fitted curves are compared. Points are observed means. Compare the result with the individual fits above: the individual comparison shows which shape describes individuals, this one which shape describes the population trajectory of the sampled records. Tick only the functions you want to compare to reduce clutter. This fit carries no lifespan or AFR term, so the preferred function can change once you add proxies. Cubic curves extrapolate poorly. With count families the exponential model a \u00b7 exp(b \u00b7 age) equals the Linear function on the log scale and is left out. 'Asymptotic exponential' is an intercept plus \u03b2 \u00b7 exp(\u2212standardised age): it is linear in its coefficients and flattens towards a plateau, with the rate fixed by the age scale. It is a different model from 'Exponential (a \u00b7 exp(b \u00b7 age))', whose rate b is estimated, and its shape depends on the age distribution of the data analysed."),
  model_settings = info_entry("Model settings",
    "Sets the error family, ageing function, random effects and which models to compare.",
    "Start simple: choose the distribution that suits your trait, keep the random intercept, add a random slope to test whether individuals differ in ageing rate, then compare AICs. The advanced options below change how among-individual terms enter.",
    "Interaction models can fit better without any age-dependent selection, because the interaction absorbs among-individual differences in ageing when random slopes are absent. If an interaction model wins, refit with random slopes and check that it holds. AIC compares models only within the same family and random structure.",
    more = "Error family, ageing function, individual-level random effects, how among-individual terms enter, standardisation, whether invalid fits may be ranked, and which models to compare. Each model row has a tick box, an 'i' explaining what it tests (ALR- or centring-based; disappearance or appearance, age-dependent or not) with its exact specification under the current covariates and random effects, and a menu to add terms to that model alone (ALR additively to Model 5 or 6, a covariate \u00d7 age). The wrench builds a term from up to three components (age, ALR, AFR, LS, mean age or a covariate) joined by + or \u00d7, for example ALR \u00d7 AFR \u00d7 age; built terms appear in that model's menu and can be removed there. Binomial families show a 'Weights' menu for the number of trials behind each proportion. Start simple. Pick the data distribution that suits your trait \u2014 continuous, count, overdispersed or zero-inflated are the common cases. The models fit a random intercept automatically; add a random slope to test whether individuals are heterogeneous in ageing. Then compare model AICs, and only afterwards reach for the detail below. You can also compare error families for count data, and compare ageing functional forms for each model you fit. Random effects: '(1 | ID)' intercept; uncorrelated '(1 | ID) + (0 + age | ID)'; correlated '(1 + age | ID)'; 'Automatic' follows the data support shown below the menu (supported at 30+ individuals with half having \u2265 3 distinct ages). Among-individual terms enter linearly by default even with quadratic or cubic ageing; 'Same polynomial order' adds their squares and cubes. The non-linear exponential fits trait = a \u00b7 exp(b \u00b7 z_age) with nlme (Gaussian only); for counts it equals the Linear function on the log link. Press 'Fit models' after any change. Interaction models can fit better even without age-dependent selective disappearance, because they absorb heterogeneity in ageing when random slopes are absent. If an interaction model looks supported, refit with random slopes where you can and check whether the result holds, and use the visual diagnostics in step 2 to work out why selective disappearance might be age-dependent. AIC compares models only within the same family and random-effect structure. Random slopes need several records per individual. Terms added to one model change what it tests, so likelihood-ratio tests are reported only for genuinely nested pairs. Including invalid fits is for inspection only. Built interactions with age multiply the ageing terms (a three-way interaction with a quadratic adds many coefficients), so they can over-fit, fail to converge or resist interpretation: compare them with simpler models. The zero-inflated negative binomial has two variance forms, nbinom2 (\u03bc + \u03bc\u00b2/\u03b8) and nbinom1 (\u03bc(1 + \u03c6)); compare them with the error-family check."),
  lrt = info_entry("Nested likelihood-ratio tests",
    "Compares nested models: pairs in which one model is a subset of the other, so the larger model contains fixed-effect terms that the smaller one does not. This assesses whether those extra fixed-effect terms are significant in explaining the data.",
    "If the smaller model is no different from the larger one (a non-significant test), the additional fixed-effect terms do not explain the data, and the simpler model is usually preferred (parsimony).",
    "Only nested pairs can be compared this way; models that are not nested are compared by AIC. A likelihood-ratio test compares two models, not the whole set, and repeated tests inflate the chance of a false positive."),
  fit_status = info_entry("Fitting status, convergence and dropped rows",
    "Shows, for each model, whether the fit converged, whether it is singular, whether its Hessian is positive definite, and which rows were dropped from all models.",
    "Converged: the optimiser found a maximum of the likelihood, so the estimates can be read; a fit that did not converge has unreliable estimates. Singular fit: a random-effect variance is estimated as zero, or a correlation between random effects as \u00b11 - the random-effect structure is more complex than the data support (for example, individuals do not differ detectably in their slopes); the fixed effects are usually still usable, but a simpler random structure is often better. Hessian not positive definite: the curvature of the likelihood at the estimates does not give a valid covariance matrix of the estimates (it implies impossible, for example negative, variances), usually because a parameter cannot be identified from the data - too many parameters for the data, terms that are almost perfectly correlated, or a variance at zero; the standard errors and p-values of such a fit cannot be trusted.",
    "Fits marked Caution can still be compared, but check them before interpreting them; fits with an invalid Hessian are excluded from the ranking. Rows with a missing value in any variable a model uses are dropped from every model, so that all models are compared on the same data."),
  model_support = info_entry("Which selective processes best explain the data?",
    "Ranks the fitted models by AIC and marks those within 2 AIC of the best, which the data do not distinguish. R2 shows how much of the variance each explains. Models 1 to 10 exist to compare selective processes against each other: disappearance and appearance, each carried either by a covariate term (ALR, AFR or lifespan) or by the centred among-individual term, and each as an age-independent or an age-dependent effect. Covariates you map enter every model additively, so this comparison asks which selective process explains the data while the rest of your model stays fixed.",
    "Read the supported set rather than the top row, and check each model's fit status before using it.",
    "AIC ranks models; it does not establish a process. A model can rank first and explain very little. Trait-dependent missingness, omitted random slopes, a misspecified ageing function and terminal decline all inflate the same AIC gap, so read the coefficients and the diagnostics before concluding. If several models have similar AICs (\u0394AIC < 2), parsimony suggests using the simpler model for biological interpretation.",
    more = "Models are fitted with lme4 (Gaussian and binomial), glmmTMB (count, zero-inflated and beta-binomial families), lmerTest for Gaussian p-values, and checked with DHARMa and performance. \u0394AIC, Akaike weights, nested likelihood-ratio tests and fitting status for Models 1\u201310 (and any extra terms), all on the same rows. Each fit is classified Valid (no warnings), Caution (boundary or singular fit, convergence-gradient warnings, rank-deficient terms dropped, or other notes) or Failed (no fit, a non-positive-definite or singular Hessian, or a non-finite AIC). Centring models (Models 3 and 5) assume ageing is absolute and depends on chronological age, so the among-individual term is transformed (for example squared) before centring, i.e. before delta age is calculated (Fay et al. 2022). \u0394AIC < 2 means similar support. Model 2 vs 4 tests age-dependent disappearance through ALR, 3 vs 5 through mean age; 2 vs 7 and 4 vs 8 test selective appearance; Models 9 and 10 let disappearance and appearance differ in age dependence (9: ALR \u00d7 age + AFR; 10: ALR + AFR \u00d7 age). Likelihood-ratio tests appear only for genuinely nested pairs. Failed fits are excluded from the ranking, weights, tests, prediction plot and automated interpretation unless 'Include fits with invalid Hessians' is ticked. Missingness that depends on the trait can produce a false positive for age-dependent selective disappearance, and Models 3 and 5 can win with no selection at all, so read this alongside the missingness drivers. Without random slopes, the interaction terms recover among-individual heterogeneity in ageing, which can make Model 4 win in the absence of any age-dependent selective disappearance. Do not use AIC as evidence for a process: read the coefficients and p-values to see why a model fits better, and use the visual diagnostics. Terminal decline does the same: check the trait-before-death figure. Integer data treated as Gaussian: confirm the trait is continuous rather than a count or 0/1 outcome. Without random slopes, interaction models can be favoured merely because individuals differ in ageing rate. A Caution fit can still inform, but compare it with a simpler random-effect structure. Rows missing any model variable are dropped from all models, so that the AIC comparison uses the same rows throughout; this only bites if you add a covariate to one model and not the others, which is inadvisable anyway. Likelihood-ratio p-values are approximate for mixed models (boundary variances, singular fits, zero inflation), and the ranking shows relative support among the models fitted, not that the best one generated the data: models within about 2 AIC have comparable support."),
  consistency = info_entry("Internal consistency of the evidence",
    "Automatic cross-checks between the model ranking and other evidence: for simulations, whether the lowest-AIC model also recovers the true trajectory most closely; whether likelihood-ratio tests agree with AIC; whether the age dependence in the lowest-AIC model agrees with the trend of the lifespan\u2013trait coefficient across age bins; whether the best fit is only classified 'Caution'; and whether interaction models win while random slopes are not fitted although the data support them.",
    "Agreement across criteria strengthens a conclusion. When they disagree, report the disagreement and prefer the more conservative reading. AIC measures how well a model describes the sampled records; recovering the latent population trajectory is a different goal, and with sparse late ages, few occasions, zero inflation or confounded appearance and disappearance the two can point to different models.",
    "The checks are heuristic and cannot detect every inconsistency; the absence of a flag is not proof that the evidence is coherent."),
  random_slopes = info_entry("Random slopes of age",
    "Lets individuals differ in how fast they age, not only in their average level, by adding a random slope of age within individual.",
    "Fit a random slope whenever the data support it, then compare the model ranking with and without it.",
    "Without random slopes the interaction models can fit better simply because individuals differ in ageing rate. To avoid reading that as age-dependent selective disappearance, refit with slopes and check the interaction p-values and the visual diagnostics.",
    more = "Lets individuals differ not only in their average level but in how fast they age, by adding a random slope of age within individual. Fit a random slope whenever the data support it, then compare the model ranking with and without it. Without random slopes, the interaction models can still fit better simply because the interaction terms recover among-individual heterogeneity in ageing. To avoid reading that as age-dependent selective disappearance, refit with random slopes and check whether the result holds."),
  varcomp = info_entry("Random effects",
    "The variance attributed to each random term: how much individuals (and any grouping levels) differ, beyond what the fixed effects explain.",
    "Compare each variance with the residual. A random-intercept variance that is large relative to the residual means individuals differ consistently in average trait level. A random-slope variance that is clearly above zero means individuals age at different rates, which is the case in which omitting random slopes can make an interaction model look supported. A variance at or near zero, often flagged as a singular fit, means that term explains nothing and can be dropped.",
    "Variances are on the scale of the fitted link, so for counts and proportions they are on the log or logit scale.",
    more = "Estimated random-effect SDs (and correlations) for each fitted model. With 'Random slope' ticked, the individual level shows an SD for the age term (f1) and its correlation with the intercept, indicating that random slopes were fitted. SDs near zero indicate boundary (singular) fits. A term is flagged when it explains no variance: less than 1% of the total variance (random terms plus residual) in Gaussian models, or a standard deviation below 0.05 on the log or logit scale in count and binomial models, which have no residual variance on that scale. Refitting without such a term usually changes little and gives a simpler, non-singular model; the individual random intercept is kept, because the repeated records of each individual need it."),
  predictions = info_entry("Model predictions trajectory",
    "Draws each model's predicted population trajectory on the trait scale, with the observed means, the decomposition and the individual-fit reconstruction available as overlays.",
    "Compare how far the corrected models sit from Model 1, which acts as a negative control by not accounting for selective processes. A difference in level indicates an age-independent association; a difference that widens or narrows with age indicates an age-dependent one.",
    "Under age-independent selection every model returns almost the same curve even when AICs differ by hundreds, because the proxy is held at its mean. Curves separate only when selection is age-dependent. Late ages rest on few individuals. For count traits, predictions describe the typical individual; when individuals differ in the shape of ageing, which the random effects here cannot represent beyond an intercept and age slope, predictions at old ages lie between the typical individual and the average of individual curves.",
    more = "Each model's predicted trajectory: (1) random effects excluded (re.form = NA), so the curve is a typical individual, not a sampled one; (2) numeric covariates held at their mean across individuals; (3) factor covariates marginalised \u2014 predicted for every observed combination of levels and averaged, weighted by how many individuals have it (or split by the factor chosen in 'Show predictions by'); (4) ALR, LS, AFR and mean-age terms held at their individual-level means (polynomial among-individual terms use the square or cube of that mean); (5) reported on the response scale, so count models include the zero-inflation probability. Observed means, the decomposition, the reconstruction from individual fits and, for simulations, the truth can be overlaid. Choose which models to draw to reduce clutter. Models that account for selective disappearance should track the truth in simulations; observed means and the decomposition are biased under age-dependent selection. With covariate \u00d7 age interactions, show predictions by that covariate to see how its levels age differently. 'Individual records (jittered)' adds every raw value as a faint point, jittered along age only. The decomposition (Rebke et al. 2010) chains the mean within-individual change between successive occasions using only individuals sampled at both; on an irregular schedule records are first placed on a common grid, and a caution appears below the figure. Curves at sparsely sampled late ages are uncertain. For counts the curve averages predictions across factor combinations on the response scale, which is not a prediction at average covariate values. Failed fits are not drawn unless included; Caution fits are dashed. Under age-independent selective disappearance every model returns almost the same curve even when AIC values differ by hundreds of units. That is expected: the proxy is held at its mean, so proxy terms contribute nothing there, and the age slope is unbiased in all the models \u2014 the AIC difference comes from explaining among-individual variation in level, not from a different trajectory. Curves separate only when disappearance is age-dependent, because then the uncorrected models estimate a biased slope."),
  decomposition = info_entry("Decomposition (Rebke et al. 2010)",
    "Reconstructs the population trajectory from within-individual change alone, using at each step only the individuals measured at both ages.",
    "The gap between this and the observed means is the contribution of selective disappearance. Nothing is fitted, so no ageing function is assumed.",
    "Unbiased when disappearance is age-independent, biased when the rate of ageing itself is linked to lifespan. Late steps rest on few pairs, and a break in the sampling grid splits the curve into segments.",
    more = "A non-parametric reconstruction of the population trajectory from within-individual change alone. Occasions are the distinct sampled ages; between each pair of adjacent occasions the app takes the mean change in the trait over only those individuals recorded at both, then chains those increments from a starting level. In symbols: the value at occasion t+1 is the value at t plus the mean of (trait at t+1 \u2212 trait at t) over individuals present at both. Nothing is fitted, so no functional form is assumed. Compare it against the observed means. Observed means mix within-individual change with the changing composition of survivors; the decomposition removes the composition change, because every increment comes from individuals measured twice. A gap between the two is the contribution of selective disappearance, and the decomposition is what the population trajectory would look like if no one had left. It is unbiased when disappearance is age-independent, and biased when the rate of ageing itself is linked to lifespan, because then the individuals contributing each increment are themselves a selected set. On an irregular schedule records are first placed on a common grid, and a break in the grid splits the curve into segments that are drawn unjoined. Late increments rest on few pairs."),
  reconstruction = info_entry("Reconstruction from individual fits",
    "Averages each individual's own fitted ageing function across the whole age range, as the parametric counterpart to the decomposition.",
    "Use it to ask what the average within-individual trajectory would be with mortality set aside.",
    "It assumes individuals are immortal and that every individual ages along the same functional form. Unreliable with few records per individual, high missingness or small samples.",
    more = "The parametric counterpart of the decomposition: each individual's own fitted ageing function from step 4 is evaluated across the whole age range and those curves are averaged, either by averaging the coefficients or by averaging the functions themselves. Use it to ask what the average within-individual trajectory would be if mortality were set aside entirely. Because each individual contributes its own fitted curve at every age, the average is not reweighted by who is still alive, so it is not shifted by selective disappearance in the way observed means are. It assumes individuals are immortal: each function is extended to ages at which that individual was never seen, and is assumed to behave the same way there. It also assumes every individual ages along the same functional form. It is unreliable with few records per individual, high missingness, small samples, or genuinely stochastic trajectories."),
  effect_sizes = info_entry("Effect sizes",
    "Reports how far the ageing slope moves when the lifespan proxy is added, how much of the trait one unit of ALR accounts for, and the difference in ageing rate between long- and short-lived individuals.",
    "Use these to say how much the correction changed the answer, not just which model won.",
    "The interval on the change in slope treats the two fits as independent, which they are not, so it is conservatively wide. Everything is on the fitted link scale, so for counts and proportions these are changes on the log or logit scale.",
    more = "Three quantities on the trait\u0027s own scale, with 95% intervals. First, how far the estimated ageing slope moves when the lifespan proxy is added (Model 1 against Models 2, 4 or 6), in absolute terms and as a percentage of the uncorrected slope. Second, how much of the trait one extra unit of ALR buys. Third, the difference in ageing rate between a long-lived and a short-lived individual, taken as the ALR \u00d7 age coefficient multiplied by the spread of ALR between its 10th and 90th percentiles. AIC says which model the data prefer; it says nothing about how much the correction changed the answer. These numbers do. \u0027Correcting for selective disappearance steepened the decline by 34%\u0027 is the sentence a reader wants, and it is the one to report alongside the model ranking. The interval on the change in slope treats the two fits as independent, which they are not, so it is conservatively wide. The percentage is unstable when the uncorrected slope is near zero. Everything is on the scale of the fitted link, so for count and binomial families these are changes on the log or logit scale, not on the count or probability scale."),
  permutation = info_entry("Null-model bootstrap against data without a lifespan effect",
    "Fits a model with no lifespan term - a flexible (cubic) ageing function, individual differences in level and in rate of ageing, and your covariates and family - and simulates new trait values from it, keeping every individual's real ages, ALR, AFR and lifespan. The chosen model and Model 1 are refitted to each simulated dataset, and the model's AIC advantage in your data is compared with the advantages in the simulations.",
    "A small p-value means data without any link between lifespan and the trait rarely give an advantage as large as yours, so the lifespan term captures a real association. Shuffling lifespans between individuals, as a permutation test does, would create records after an individual's last record or death, so anything tied to the observation window - a misspecified ageing function, a change just before death - would beat every shuffle. Simulating the trait keeps the real observation windows. The test counts in the evidence summary only when it is run on the model the finding rests on, with the same data and settings.",
    "The default is 39 simulated datasets. The smallest possible p-value is 1 / (n + 1) for n refitted datasets, so at least 19 must be refitted to reach p < 0.05; 39 leaves room for a few failed refits. A change in the trait just before death is still a link to lifespan, so check 'Is there terminal investment?' in step 2 when the result is significant."),
  evidence = info_entry("Evidence summary",
    "Grades the evidence in the results you saved, separately for selective disappearance and selective appearance.",
    "Save results from steps 2 to 5 and the summary updates as you save or remove them. The level is strong only when every check relevant to the finding has been saved and has passed.",
    "It reads only saved results, so an exploratory result saved by mistake is counted. It grades the evidence for a pattern; it does not establish the mechanism behind it.",
    more = "Which saved results feed which line. Visual pattern: the trajectory, gap or trait-against-lifespan figures in step 2. Model comparison and the lifespan term: the latest model comparison in step 5 fitted with a random intercept only (or, if none was saved, the latest comparison). Random-slope sensitivity: a model comparison of the same analysis saved after refitting with random slopes; if it disagrees, the evidence is weakened rather than replaced. The finding's direction is read from the predictions of the model it rests on. Ageing shape: the Ageing-function check, or the automatic check saved with the model comparison; a manual check counts only for the function actually fitted, and not when it was run on Model 1 for a finding about selection. Null-model bootstrap: step 5, Advanced, run on the model the finding rests on (for example Model 4 for an age-dependent finding) with the same data and settings. Results from an earlier analysis with other settings are set aside. Observation bias: the missingness results in step 3."),
  detection = info_entry("Detection probability",
    "The share of expected occasions at which an individual carrying a record was actually recorded.",
    "Read it with the sampling window in mind: its value depends on whether missingness is counted only between an individual's first and last record, or from the age at which the trait is first expressed.",
    ""),
  accuracy = info_entry("How close is each model to the known truth?",
    "The true trajectory here is what ecologists want to estimate from longitudinal data: the average within-individual trajectory, latent to the researcher but inferable from cohort-level data. Relativised deviation D = 100 \u00d7 (estimate \u2212 truth) / truth (Methods Eq. 11) for each model, observed means and the decomposition.",
    "Smaller mean |D| is better.",
    "Simulations only; restricted to ages with at least 10 observed individuals."),
  coefficients = info_entry("Coefficients, scaling and interpretation",
    "Fixed-effect estimates, standard errors and tests for the selected model, with the scaling constant behind each coefficient, the estimate per original unit, the random-effect variances, and a plain-language reading of the selective disappearance or appearance terms. Scaling: with standardisation, age = (age \u2212 centre) / SD and ALR, LS and AFR are standardised across individuals; a term's scale factor is the product of the SDs of its components (for example SD\u00b2 for age\u00b2, SD_age \u00d7 SD_ALR for age \u00d7 ALR). Estimate per original unit = estimate / scale factor: the coefficient per unit of the centred original variables (for example per year of ALR, or per (age \u2212 centre)\u00b2). Numeric covariates are not standardised. Count models are on the log scale.",
    "The interpretation compares predicted trajectories for individuals at the 10th and 90th percentiles of ALR (or LS, AFR, mean age) at a young, middle and old age. If only the additive term is supported, longer- and shorter-lived individuals differ by a similar amount at all ages (age-independent selective disappearance). If the interaction is supported, the gap changes with age (age-dependent), for example longer-lived individuals having higher trait values mainly at older ages.",
    "Standardisation aids numerical stability; the per-unit column translates coefficients back to biological units. P-values are Satterthwaite t-tests for Gaussian fits when lmerTest is installed and asymptotic Wald z-tests otherwise (see the 'P type' column); likelihood-ratio tests are used where models are nested. The interpretation is an association conditional on the model, not proof of selection: check it against the visual diagnosis plots, residual diagnostics and alternative random-effect structures. Standardised coefficients are expressed on the age scale of the data analysed, so they change if the sample or its age range changes."),
  definitions = info_entry("Model definitions",
    "Fixed effects and the question addressed by each ticked model, with the chosen covariates and interactions.",
    "Models 3 and 5 separate within- and among-individual age effects; Model 6 needs known lifespan; Models 7\u201310 add AFR (age at first observation). Click the 'i' next to a model in the settings for its exact specification, including terms added to that model.",
    "Covariates enter every model; interactions chosen on the Data tab are added to every model; terms added in a model's menu apply only to that model."),
  function_check = info_entry("Ageing-function check",
    "Refits any model with each ageing function in turn, so you can test whether a different shape describes the data better.",
    "Use it when the shape you chose is not clearly the best-supported one at the individual or population level.",
    "A misspecified ageing function makes the model inaccurate, and the interaction or random terms will often absorb the misspecified shape - which can look like age-dependent selective disappearance. When this disagrees with the individual-level comparison in step 4, rely on this one: it compares functions within the same model and uses all the data at once.",
    more = "Researchers often misidentify or misspecify the average ageing function in their models. The previous step lets you evaluate visually, at the individual and population level, what the underlying average ageing function might be; this diagnostic refits any of Models 1 to 10 with each ageing function in turn. The age terms change with the function, and the rest of the model follows: for Model 4, a quadratic fits trait ~ age + age\u00b2 + ALR + age \u00d7 ALR + age\u00b2 \u00d7 ALR, a cubic adds age\u00b3 and age\u00b3 \u00d7 ALR, and a logarithmic fits trait ~ log(age) + ALR + log(age) \u00d7 ALR. Use it to test whether a different ageing function describes your data better. For counts the truth is the typical individual's curve, so observed means differ from it even without selection. The models let each individual have its own intercept, and its own age slope if chosen, but not its own curvature, so when individuals differ in the shape of ageing the predictions at old ages can drift from the truth even when the model structure is right."),
  family_check = info_entry("Error-family check",
    "Refits a model with each count family, so you can see which distribution suits the trait.",
    "Compare AICs across families and check the dispersion. Zero inflation is worth testing whenever zeros are common.",
    "AIC compares families only on the same rows and the same model. A family that fits better can still produce implausible predictions.",
    more = "Refits one model with each count family and compares AIC. Choose the lowest AIC among count families, then check residuals. Not comparable with a Gaussian AIC; zero-inflated models can be slow or fail to converge."),
  dharma = info_entry("Are my data overdispersed or underdispersed?",
    "Simulation-based residual checks for the fitted model: whether residuals are uniform, whether the data are more or less variable than the error family expects, and whether there are more zeros than expected.",
    "A good model gives a QQ plot whose points follow the diagonal and a residual-versus-fitted plot with no pattern, and non-significant uniformity, dispersion and zero-inflation tests. Points bending away from the diagonal, or a fan or curve in the residuals, indicate a problem.",
    "In large datasets trivial deviations become statistically significant, so judge the plots rather than the p-values alone.",
    more = "Reading the plots in more detail. Overdispersion shows as a dispersion ratio well above 1 and residuals spread wider than the simulated ones: move from Poisson to negative binomial. Underdispersion shows as a ratio well below 1 and residuals bunched towards the middle: common with bounded counts, and it makes intervals too wide rather than too narrow. Excess zeros show as a zero-inflation test with a ratio above 1: try a zero-inflated family. A curved band in the residual-versus-fitted plot means the ageing function or a covariate is misspecified, not the error family. Outliers flagged in red are observations more extreme than every simulation; check them for recording errors before removing anything. Simulation-based residual tests for uniformity, dispersion and zero inflation, with diagnostic plots. Small p-values indicate that the error distribution or model structure fits poorly. In large datasets trivial deviations become significant: judge the plots."),
  performance = info_entry("Does my model violate assumptions such as homoscedasticity or normality of residuals?",
    "Assumption checks for the selected model from the performance package: homogeneity of variance, normality of residuals and of random effects, influential observations, collinearity and, for counts, overdispersion and zero inflation.",
    "A good model shows a flat, even band in the homogeneity panel, points close to the line in the normality panels, no points beyond the influence contours, and low collinearity. A funnel in the homogeneity panel, strong curvature in the normality panels, or isolated points outside the contours indicate a violation.",
    "Mixed models are fairly robust to mild departures from normality. Heteroscedasticity and influential points matter more, because they distort both the estimates and their standard errors.",
    more = "Reading the panels in more detail. Homogeneity of variance: a funnel widening with fitted values suggests a count or log-scale trait modelled as Gaussian - try a count family or a log transform. Normality of residuals: heavy tails or an S-shape suggest the wrong family or outlying individuals. Normality of random effects: a skewed distribution suggests a subgroup of individuals behaving differently, worth modelling as a covariate. Influential observations: points outside the Cook's distance contours shift the estimates on their own; refit without them to see whether conclusions change. Collinearity: a variance inflation factor above about 5 to 10 means two predictors carry overlapping information, which is expected between age and its polynomial terms and between ALR and mean age, and inflates their standard errors. Singular fits mean a random-effect variance is estimated at zero: simplify the random structure. Checks from the performance package for the selected model: Nakagawa R\u00b2, intraclass correlation, singularity, convergence, collinearity and, for counts, overdispersion and zero inflation, plus the performance::check_model() diagnostic panels (needs the see package). Use these alongside the DHARMa residual checks: singular fits suggest simplifying the random effects; overdispersion suggests a negative binomial family; a zero-inflation ratio well below 1 suggests a zero-inflated family. Not every check supports every model type (for example some zero-inflated glmmTMB models): unavailable checks are reported rather than stopping the app. Polynomial and interaction terms are collinear by construction. check_model() can be slow on large datasets."),
  rcode = info_entry("Reproducible R code",
    "A script that reproduces the model comparison with lme4 or glmmTMB.",
    "Run it on your data file to reproduce or extend the analysis.",
    "It assumes the same column names and settings as the app."),
  saved = info_entry("Saved results",
    "The results you saved from other tabs. They make up the exported HTML report (with plots) or text report.",
    "Remove items you no longer need before exporting.",
    "Saved items are snapshots: they do not update when the data or settings change."),
  overview_auto = info_entry("Automatic overview",
    "An automatic summary of the current data and settings.",
    "Use it as a checklist of where to look, not as a conclusion. Save it to include it in the report.",
    "")
)


# Collapsible box with the R code that reproduces a section (the minus sign hides it)
section_code_box <- function(section) {
  fluidRow(box(width = 12, title = "R code for this section", status = "info", solidHeader = TRUE, collapsible = TRUE,
    p(class = "small-note", "A script that reproduces this section with the current settings. The app's own helper functions are included, so it runs on its own (packages: ggplot2; lme4, and glmmTMB or nlme where models are fitted). If you uploaded a file, put it in R's working directory."),
    div(class = "code-toolbar",
        tags$button(type = "button", class = "btn btn-default btn-sm", onclick = sprintf("disapprCopy('code_%s_text', this)", section), icon("copy"), " Copy"),
        downloadButton(paste0("download_code_", section), "Download .R", class = "btn-default btn-sm")),
    div(class = "section-code", verbatimTextOutput(paste0("code_", section, "_text")))))
}

info_title <- function(title, key) {
  tags$span(title, actionLink(paste0("info_", key), label = "", icon = icon("circle-info"),
                              class = "info-link", title = "What is this, and how do I read it?"))
}

info_body <- function(e) {
  has <- function(x) !is.null(x) && length(x) && any(nzchar(trimws(as.character(x))))
  tagList(
    if (has(e$lead)) p(e$lead) else NULL,
    if (has(e$what)) tagList(h5(strong("What it does")), p(e$what)) else NULL,
    if (has(e$how)) tagList(h5(strong("How to use and interpret it")), p(e$how)) else NULL,
    if (has(e$caution)) tagList(h5(strong("Cautions")), p(e$caution)) else NULL,
    if (has(e$more)) tags$details(class = "info-more", tags$summary("More info"),
                                  div(class = "info-more-body", p(e$more))) else NULL
  )
}

# ---------------------------------------------------------------------------
# Guidance layer. These helpers add signposting only: what this tab is for, what to open first,
# what to look at in a figure, and which controls are recommended rather than required. They do not
# change any analysis, setting or default.
# ---------------------------------------------------------------------------

# The six numbered steps of the workflow, used by the progress strip and the Previous/Next buttons.
WORKFLOW_STEPS <- data.frame(
  tab = c("data", "visual", "sampling", "individual", "models", "summary"),
  label = c("Data", "Visual diagnosis", "Missingness and proxies", "Trajectories", "Modelling", "Report"),
  stringsAsFactors = FALSE
)

# "What to do here" panel: the goal of a tab, what to open first, what follows, and where to go next.
guide_box <- function(tab, goal, start_with, then = NULL, tip = NULL) {
  i <- match(tab, WORKFLOW_STEPS$tab)
  nxt <- if (!is.na(i) && i < nrow(WORKFLOW_STEPS)) WORKFLOW_STEPS$tab[[i + 1]] else NULL
  prv <- if (!is.na(i) && i > 1) WORKFLOW_STEPS$tab[[i - 1]] else NULL
  div(class = "guide-box",
      div(class = "guide-head", "What to do here"),
      div(class = "guide-goal", goal),
      div(class = "guide-step", tags$span(class = "guide-lab", "Start with:"), start_with),
      if (!is.null(then)) div(class = "guide-step", tags$span(class = "guide-lab", "Then:"), then) else NULL,
      if (!is.null(tip)) div(class = "guide-tip", tip) else NULL,
      div(class = "guide-nav",
          if (!is.null(prv)) actionLink(paste0("go_prev_", tab), paste0("\u2190 ", WORKFLOW_STEPS$label[[i - 1]]), class = "guide-link") else NULL,
          if (!is.null(nxt)) actionLink(paste0("go_next_", tab), paste0(WORKFLOW_STEPS$label[[i + 1]], " \u2192"), class = "guide-link guide-link-next") else NULL))
}

# The page's question, shown above the guidance panel.
page_title <- function(txt) div(class = "page-title", txt)

# What the four box colours mean. Shown once, on the first numbered tab.
evidence_key <- function() {
  div(class = "evidence-key",
      tags$span(class = "ek ek-primary", "Primary"), " read this now \u00b7 ",
      tags$span(class = "ek ek-sens", "Sensitivity"), " could overturn it \u00b7 ",
      tags$span(class = "ek ek-support", "Supporting"), " corroboration \u00b7 ",
      tags$span(class = "ek ek-tech", "Technical"), " diagnostics and code")
}

# One sentence under an output telling the reader what to look at.
look_for <- function(...) div(class = "look-for", tags$span(class = "look-lab", "Look for:"), ...)

# A short, consistent status label so that recommendations are not mistaken for requirements.
badge <- function(kind) {
  txt <- switch(kind,
    recommended = "Recommended starting point",
    optional = "Optional sensitivity check",
    required = "Required for this analysis",
    caution = "Caution",
    unavailable = "Not available with these data",
    kind)
  tags$span(class = paste0("dbadge dbadge-", kind), txt)
}

# A plain-language question above the technical name of a panel, with the "i" help kept intact.
plain_title <- function(question, technical, key) {
  tags$span(class = "plain-title",
            tags$span(class = "plain-q", question),
            tags$span(class = "plain-t", info_title(technical, key)))
}

# Divider between the outputs most users need and the deeper checks.
section_divider <- function(label, note = NULL) {
  div(class = "section-divider", tags$span(class = "section-divider-label", label),
      if (!is.null(note)) tags$span(class = "section-divider-note", note) else NULL)
}

save_button <- function(id, label = "Save to summary") {
  actionButton(id, label, icon = icon("bookmark"), class = "btn-default btn-sm save-btn")
}

# ---- Moved unchanged from inst/app/server.R (0.9.11): pure helpers that use no reactive state ----

# Errors inside observers would otherwise end the session (the page turns grey and stops responding).
# Every observer runs inside this guard: the error is reported on screen and in the R console instead.
disappr_guard <- function(where, expr) {
  tryCatch(expr,
           shiny.silent.error = function(e) invisible(NULL),
           error = function(e) {
             msg <- paste0("Something went wrong (", where, "): ", conditionMessage(e))
             message("disappR: ", msg)
             try(showNotification(msg, type = "error", duration = 20), silent = TRUE)
             invisible(NULL)
           })
}

num_input <- function(x, default) {
  v <- suppressWarnings(as.numeric(x))
  if (length(v) != 1 || !is.finite(v)) default else v
}

safe_get <- function(expr) tryCatch(expr, error = function(e) NULL)

metric_card <- function(label, value, sub = NULL, width = 3) {
  column(width, div(class = "metric-card", div(class = "metric-label", label), div(class = "metric-value", value),
                    if (!is.null(sub)) div(class = "metric-sub", sub)))
}
